### ISSUE TITLE
Fix problem with 8192cu wireless chip (solution included)

### ISSUE THREAD

**Issue by BartOtten** [xbianonpi/xbian#217]
Source: http://forum.xbian.org/thread-37-post-2088.html#pid2088

The 8192cu wireless chip found in many wifi dongles on ebay (mine is Edup) has some power issues with raspberry pi. Mine was repeatedly disconnecting and going into saving mode or something even thought it dosne't really have power management features.

You have to create a file:

```
sudo nano /etc/modprobe.d/8192cu.conf
```

and add this line:

```
# Disable power saving
options 8192cu rtw_power_mgnt=0
```

save and reboot.

you can check the status if it is off:

```
cat /sys/module/8192cu/parameters/rtw_power_mgnt
```

it should be 0 now.

**Comment by thayoz** [comment]
Thanks a lot for the fix !
