### ISSUE TITLE
Save (all) XBian settings support for easy reinstallation

### ISSUE THREAD

**Issue by CurlyMoo** [xbianonpi/xbian#271]
How cool would it be if you would just be able to click "Save XBian settings" and then store those settings somewhere (online). When you then need to do a reinstall you can click "Load XBian settings" and the system brings itself into it state where it was in before the reinstall. Things that i'm thinking about:

- Install all (previously installed) xbian-packages
- Restore network configuration
- Restore hostname
- Restore all settings file (e.g., samba, apache, php, sickbeard, couchpotato, transmission, nzbget, headphones)
- Locales / language
- SSH root login
- /boot/config.txt (e.g., connectivity settings, licenses)
- /boot/cmdline.txt
- Remaining xbian-config settings
- Let users add files to the backup themselves.

This feature can be synced with the backup functionality as suggested by @BartOtten.

Massively cool ideas:
- Automatically every day/week/month.
- Link XBian settings to xbian.org user account and store them online (in a truecrypt container for safety).
- Add functionality to the xbian-installer to automatically download the settings and putting them on the SD card (by logging into the user account). At first boot, xbian-config will restore to it's previous state.

**Comment by mkreisl** [comment]
Can be done by automated backup /home and complete image backup
