### ISSUE TITLE
Installer failure

### ISSUE THREAD

**Issue by patricktokeeffe** [xbianonpi/xbian#353]
Downloaded the installer less than an hour ago (read: current) and it won't launch for me. After setting `chmod +x` I get the following:

``` bash
$ ./XBian-installer
bash: ./XBian-installer: cannot execute binary file
$ sudo ./XBian-installer
./XBian-installer: 1: ./XBian-installer: Syntax error: "(" unexpected
```

on xubuntu 12.04 x64

**Comment by fzzylogic** [comment]
Fwiw, i had the same problem from a 32bit system (Xubuntu 14.04.3). Followed instructions at https://github.com/xbianonpi/xbian-installer-universal to compile for my system. Only change was had to edit Makefile and change path of qmake to /usr/bin/qmake. XBian-installer built fine and worked as usual.
