### ISSUE TITLE
XBMC Freezes after long uptime ( libcec ? )

### ISSUE THREAD

**Issue by Flos** [xbianonpi/xbian#380]
My XBMC keeps freezing up after a longer time periods (a few days). 

If i turn on the TV and switch to the hdmi channel connected to xbian, I see the information of the Pulse-Eight CEC Adapter: "configuration updated" and the frozen clock. 

SSH just works fine in this situation. 
here is the xbmc.log  http://pastebin.com/Vx4F1mw7

To get it back to work I have to restart the xbian by unplugging the powercord. 

top shows:
 3474 xbian     17  -3     0    0    0 Z   0.0  0.0   1187:48 xbmc.bin 

Im unable to fix it with ssh:

sudo /etc/init.d/xbmc restart
sudo /etc/init.d/xbmc stop

sudo kill xbmc
sudo killall xbmc
sudo kill -9 xbmc 
sudo kill -9 3474 

sudo shutdown -r now 

dosent work.

I still se the freezed xbmc screen on my tv.
and also ssh is not closing the connection.

Any ideas ?

**Comment by AykutCevik** [comment]
I have experienced this issue today with latest xbian for rpi2, "service xbmc restart" did not solve the problem, made a "sudo reboot", which did the job. Will gather more infos and post them here.
