### ISSUE TITLE
Incorrect Map Keyboard

### ISSUE THREAD

**Issue by txutxifel** [xbianonpi/xbian#381]
Hi,
First of all, I would like to thank for your amazing job. Xbian work very stable and have all I need.

I have working Xbian with only one problem. Some special keys don't work, e.g:  Mute, volume down... I tried to find a solution, but I don't know what happend. 

It is not very important and I can live with this, but, anyway, do you have any idea about this?

**Comment by f1vefour** [comment]
This is a local configuration issue not global, closing.
