### ISSUE TITLE
Adding 2 options to /etc/ssh/sshd_config - speeding up SSH massively

### ISSUE THREAD

**Issue by ventz** [xbianonpi/xbian#418]
Hi,

Would it be possible to add to /etc/ssh/sshd_config:

UseDNS no
AddressFamily inet

The first one is a bit obvious - it will ignore the reverse resolution, thus speeding up the connection. Almost everyone usually adds that one. The second however, starting with Ubuntu 12.04, it seems that it attempts to connect via ipv6 and ends up falling back to ipv4. This takes time. By specifying 'inet' as the family, it will only attempt to ssh in via ipv4.

**Comment by andrew-scorchsoft** [comment]
> This is just impossible.
> 
> If IPv6 is not enabled (i.e. module not loaded) it won't bind on IPv6 (how can it do?).
> 
> Furthermore, SSHd is started behind inetd on default installs, at least as of current releases. I'm going to revert `AddressFamily inet` if nobody voices against. It's just silly to enforce IPv4 if the user manually enabled IPv6.

Horray! I can confirm this solution worked for me. Running ssh -vv git.bitbucket.org was using an IPv6 address. I added that line to the 

> Hi,
> 
> Would it be possible to add to /etc/ssh/sshd_config:
> 
> UseDNS no
> AddressFamily inet
> 
> The first one is a bit obvious - it will ignore the reverse resolution, thus speeding up the connection. Almost everyone usually adds that one. The second however, starting with Ubuntu 12.04, it seems that it attempts to connect via ipv6 and ends up falling back to ipv4. This takes time. By specifying 'inet' as the family, it will only attempt to ssh in via ipv4.

Horray! I can confirm this solution worked for me. Thank-you for your reply.

**Comment by slintz** [comment]
This solved my problem-case: Ansible very slow connecting to remote target.

FYI - Ansible makes many _**(many!)**_ SSH connections in the course of it's regular process. It just keeps reaching out - and when "UseDNS no" was in place my Ansible task times dropped from minutes to seconds - each task, for each target system. Saved me years of wait time...
