### ISSUE TITLE
[Beta 1.1] xbmc doesn't shutdown after update xbian-package-firmware 1.4-4

### ISSUE THREAD

**Issue by Mafarricos** [xbianonpi/xbian#448]
After update firmware 1.4-4 in xbian 1.0 beta 1.1 when I choose shutdown it reboots...

**Comment by adamlwgriffiths** [comment]
This seems to still be an issue with Xbian 1.0rc3, out of the box.

**Comment by mk01** [comment]
seems strange that last FW properly doing HALT(not REBOOT) is from a year back. I will retest but anyhow, can you open a issue directly at raspberry/firmware ? or at least do a quick search on past issues if there is similar ?

then we can ping popcornmix and ask him ... if this is really issue or by some magic it is only related to XBian (but no idea how it could be possible).

**Comment by mk01** [comment]
does any of this make a difference ? one is poweroff, second halt. very very long ago one was working, the second not.

sudo shutdown -H now
sudo shutdown -P now

**Comment by adamlwgriffiths** [comment]
Sorry, I had too many issues with xbian and changed distro.
If I put it back on (distro hopping) I'll recheck.
I think just before I changed over, Xbian did manage to perform a proper shutdown for the first time.
