### ISSUE TITLE
Analog audio delayed in dual output mode after jumping during video playback

### ISSUE THREAD

**Issue by sschmitz** [xbianonpi/xbian#489]
My pi is currently hooked up to a TV via HDMI and to speakers over the analog output, running 1.0beta2. I have enabled dual audio output in the XBMC settings. When playing a video, I can hear a slight delay between the audio from the speakers (first) and the audio from the monitor (second), but I think this might be the crappy TV's fault (I also cannot quite tell yet which audio channel seems to be more in sync with the picture). However, when jumping to a different position in the video, the sound coming from the analog speakers lags probably 300ms behind the sound (and image) from the TV.

This does not seem to happen with analog output only. I'm using a HDMI-driven DMT mode (as I said, crappy display ...), if that's relevant.

**Comment by CurlyMoo** [comment]
?
