### ISSUE TITLE
[Request] Add FBTFT for (cheap) SPI TFT screen support

### ISSUE THREAD

**Issue by CurlyMoo** [xbianonpi/xbian#498]
Can you guys add support for the kernel driver FBTFT so we can use cheap ebay TFT + touch screens through GPIO?

https://github.com/notro/fbtft

**Comment by f1vefour** [comment]
Added, closing issue.

**Comment by barrystaes** [comment]
@f1vefour can you link to the commit/merge/pull that added this feature?

**Comment by f1vefour** [comment]
https://github.com/xbianonpi/xbian-package-kernel/commit/26b58346c319b02cb2f3bd34efea6051b866bd16
