### ISSUE TITLE
new build tools won't run

### ISSUE THREAD

**Issue by bairdy** [xbianonpi/xbian#561]
when trying the new autobuild tools the first command 

cd xbian; ./run.me prepare

wont run the buildroot script to prepare the build environment i just get the error in clean installs of debian 7.5 or ubuntu 14.04

![debian build](https://cloud.githubusercontent.com/assets/1903701/3417480/65ca2650-fe39-11e3-91d7-0ec5c3a0a350.png)

and running the command on its own to initialize a buildroot doesn't work. i have tried changing the permissions and also making executable but it doesn't make any difference

![debian build1](https://cloud.githubusercontent.com/assets/1903701/3417521/d17b5342-fe39-11e3-8146-56858f30755a.png)

**Comment by CurlyMoo** [comment]
Run fine in a live environment.
