### ISSUE TITLE
[CuBox-I] Disable xbian-config modules

### ISSUE THREAD

**Issue by CurlyMoo** [xbianonpi/xbian#569]
The following xbian-config modules should be removed on the CuBox-i:
- Overclocking
- Video Output
- Kernel
- Licenses

Not sure if this is already adapted:
- Boot settings

**Comment by belese** [comment]
I suppose i can close.

**Comment by CurlyMoo** [comment]
Is this done?

**Comment by belese** [comment]
Yes, since :
https://github.com/xbianonpi/xbian-package-config-xbmc/commit/4614292a9706a90ccb413df80959d0ba3fedf05b

**Comment by CurlyMoo** [comment]
It's good for us to know what commit fixes it. Can you point to them in the other issues you closed as well?
