### ISSUE TITLE
Xbian's installer for Linux doesn't detect SD card or versions

### ISSUE THREAD

**Issue by wonx** [xbianonpi/xbian#583]
The title is pretty self explanatory. When I run the installer, both the Version and the Sd card menus are empty.

![captura de 2014-07-27 12 45 57](https://cloud.githubusercontent.com/assets/2736639/3713652/378d06e6-157b-11e4-8a93-6c41530f1563.png)

Obviously, i'm trying it from X11 in a x64 system. (Ubuntu 14.04).

Installers for other distributions are able to find my Sd card properly...

**Comment by CurlyMoo** [comment]
Should be fixed a few weeks ago.
