### ISSUE TITLE
[CuBox-I] [Nightlies] General discussion

### ISSUE THREAD

**Issue by CurlyMoo** [xbianonpi/xbian#604]
xbian-image-imx6-20140830.img.xz
======================================
1. U-Boot: `spl: error reading image u-boot.img, err - -1`
2. Kernel is sadly 3.10.15 again, i expected 3.14.y.
3. Serial doesn't work out of the box, but with a kernel upgrade it does.
4. BTRFS send/receive still broken.

Conclusion, nothing really new here :) Haven't tested further. Anything else you want me to test?

**Comment by mk01** [comment]
hostname is fixed
localisation @belese 
what is "ssh enable screen text" ?
btrfs-snap is also fixed

**Comment by CurlyMoo** [comment]
![xbian-config](https://cloud.githubusercontent.com/assets/2429105/5898061/cfa51ac6-a54b-11e4-93d5-2e8992ffe889.jpg)
