### ISSUE TITLE
xbian-config: Not possible to disable network interfaces

### ISSUE THREAD

**Issue by VegarS** [xbianonpi/xbian#615]
Xbian-config has no option to disable interfaces once they've been configured. The bug is especially relevant for the cubox-i which has both wired and wifi interfaces. Once the wifi interface has been configured, it can't be disabled.

Workaround: Running `sudo ifdown wlan2` disables the wifi interface until the next reboot.

**Comment by VegarS** [comment]
@mk01 
Sorry for the delay. I tested with xbian-package-config-shell version 2.1.15-1 from the stable repository (installed today). Results are the same as in October. I select disabled in the menu, but it continues to ask about SSID/WPA key and then connects. The interface also comes up after a reboot.

Is it possible that my /etc/networking/interfaces is broken or breaks config-shell?

**Comment by mk01** [comment]
@VegarS 

replace ssid/psk with ## and post it please. I will debug exactly your file.
xbian-config is designed to 'allow' user/other tools edits to system config files (so if system scripts are still reading your /networking file ok, it should too). but here it looks like it is not parsed/not able to update correctly.

**Comment by VegarS** [comment]
I was unable to attach the file here, so I'm pasting the contents below. I have never edited the file by hand, it has always been managed by xbian-config. Note that there's an entry for wlan0, which I do not have (only wlan2 is listed by ifconfig -a). SSID is replaced with $$$$$, PSK with #####.

####### Start file #######
auto lo
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

iface lo inet loopback
iface eth0 inet dhcp


allow-hotplug wlan0
iface wlan0 inet dhcp


allow-hotplug wlan2
iface wlan2 inet dhcp

wpa-ssid $$$$$
wpa-psk #####








nwireless-key #####

nwireless-key #####


####### End file #######

**Comment by VegarS** [comment]
@mk01 
I was unable to attach the file here, so I'm pasting the contents below. I have never edited the file by hand, it has always been managed by xbian-config. Note that there's an entry for wlan0, which I do not have (only wlan2 is listed by ifconfig -a). SSID is replaced with $$$$$, PSK with #####.

####### Start file #######
auto lo
\# interfaces(5) file used by ifup(8) and ifdown(8)
\# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

iface lo inet loopback
iface eth0 inet dhcp


allow-hotplug wlan0
iface wlan0 inet dhcp


allow-hotplug wlan2
iface wlan2 inet dhcp

wpa-ssid $$$$$
wpa-psk #####








nwireless-key #####

nwireless-key #####


####### End file #######

**Comment by mk01** [comment]
@VegarS 

the disable function was missing flush on interface so it still had IP (although the IF was properly disabled in "interfaces" file and taken down in system), also it is displayed properly with no IP (disabled) in xbian-config after deactivation... version -4 of xbian-package-config-shell was pushed to apt repo.

the second problem - parsing - the "look" as you provided is broken - probably happened with some early tests of yours with xbian-config/disable function not fully ok yet. 

I would recommend remove all relevant to wlanX, then try again. 

I wanted to test your environment, but could not get dummy IF to behave as wlan :( , so could not. when I find some usb adapter (I should have), I will attach to cubox to have TWO wlans and will test too.

**Comment by VegarS** [comment]
@mk01 
Ok, I have upgraded to xbian-package-config-shell 2.1.15-4 and removed all wlan entries from /etc/network/interfaces. I ran xbian-config and set up wlan2 with the correct SSID and WPA key. It connects correctly.

I then run xbian-config again and try to disable wlan2. When I select "disable" in the menu, it still continues to ask for SSID and WPA key, then connects to the network and remains up. IP address is also shown in xbian-config.
```
vegar@cubox:~$ /sbin/ifconfig wlan2
wlan2     Link encap:Ethernet  HWaddr b8:5a:f7:82:6e:77  
          inet addr:172.16.16.10  Bcast:172.16.16.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:201280 errors:0 dropped:14 overruns:0 frame:0
          TX packets:13324 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:20595183 (19.6 MiB)  TX bytes:2008130 (1.9 MiB)
```

Here is my new interfaces file, after disabling wlan2 in xbian-config:
```
auto lo
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

iface lo inet loopback
iface eth0 inet dhcp

allow-hotplug wlan2
iface wlan2 inet dhcp

wpa-ssid $$$$$
wpa-psk #####
```

Should I be worried about only lo being brought up automatically (line 1 in interfaces), or is there an external script that bring up eth0?

I discovered that my /etc/init/networking.conf is different than the one provided by the ifupdown package. Is this something xbian-update modifies, or should I try to restore the original networking.conf?

To clarify: I only have one wifi interface (wlan2). I have no idea what wlan0 was or where it came from.

**Comment by VegarS** [comment]
Appears to be working for me too now, after having reinstalled xbian (due to SD card failure).

**Comment by mkreisl** [comment]
@VegarS 

> To clarify: I only have one wifi interface (wlan2). I have no idea what wlan0 was or where it came from.

Look into the file `/etc/udev/rules.d/70-persistent-net.rules`. There you'll find all network assignments
