### ISSUE TITLE
Small typo inside xbian-config's XBMC GUI ("Vnc Serveur")

### ISSUE THREAD

**Issue by joschh** [xbianonpi/xbian#624]
As the title describes, there is a small typo inside xbian-config's XBMC GUI: "Serveur" -> "Server"

![xbian-typo](https://cloud.githubusercontent.com/assets/4521166/4419701/9f6b9e44-456e-11e4-9f9d-bdf91f56f57b.jpg)

**Comment by belese** [comment]
Fixed with this commit : 
https://github.com/xbianonpi/xbian-package-config-shell/commit/efab55749c355b93d672fc69464016d47337be05
