### ISSUE TITLE
[RPI] Xbian-package-xbmc-alsa dvdplayer issue

### ISSUE THREAD

**Issue by bairdy** [xbianonpi/xbian#633]
The builds on the repo (xbian-package-xbmc-alsa_13.2-1410511926_armhf.deb & also xbian-package-xbmc-alsa_13.2-1411446747_armhf.deb) dvdplayer isn't working correctly, it plays the first few fames of video before freezing from MP4 & AVI and audio continues, when it comes to MKV in 720p or 1080p it plays the audio but no video just a black screen.

but when it comes to using dvdplayer in the normal xbian-package-xbmc (xbian-package-xbmc_13.2-RLS-1411559513_armhf.deb) all works fine with no issues

**Comment by anaconda** [comment]
I believe the dependency issues have been fixed. Original issue seems solved too, so I'm closing this. Thanks for reporting back.
