### ISSUE TITLE
Rebrand to Kodi

### ISSUE THREAD

**Issue by anaconda** [xbianonpi/xbian#642]
As of now one needs to manually set `DAEMON=/usr/local/lib/kodi/kodi.bin` in /etc/default/xbmc if using nightlies. This will change when Kodi hits stable.

- [x] Move home directory from `.xbmc` to `.kodi`. [1]
- [x] Make `/usr/local/share/xbmc` a symbolic link to `/usr/local/share/kodi` - it is currently needed by the Upstart bridge and plugin.xbianconfig add-ons. This will change when Kodi hits stable. [1]
- [x] Make $HOME/.xbmc a symbolic link to $HOME/.kodi, just to be sure. This is also needed by plugin.xbianconfig as it tries to access .xbmc directly. [1]
- [x] Adapt plugin.xbianconfig to use $HOME/.kodi if it exists, or use .xbmc if it doesn't.
- [x] xbian-config (CLI) tries to access $HOME/.xbmc multiple times. It needs to be adapted like plugin.xbianconfig.
- [ ] ...

[1] This was added to the postinst of xbian-package-xbmc ({imx6,rpi}-nightly **only**.)

/etc:
- [x] Replace all occurrences of xbmc.bin with `$(basename $DAEMON)`. Needs `[ ! -e /etc/default/xbmc ] || . /etc/default/xbmc` and `env DAEMON=/usr/local/lib/xbmc/xbmc.bin`
- [ ] ...

**Comment by mk01** [comment]
the only thing a miss here is actually move package v14 to stable from staging. do we have any stoppers for this ?

**Comment by anaconda** [comment]
As you've adjusted `DAEMON` to be somewhat "dynamic" (from what I recall), I can't see any.
The 2 XBian add-ons (xbian-package-config-xbmc and xbian-package-xbmc-upstart-bridge, or whatever they're called) need to be moved from for `/usr/local/share/xbmc/addons` to `/usr/local/share/kodi/addons`, possibly with a dependency on xbian-package-xbmc (-kodi?) >= 14.0-...

**Comment by anaconda** [comment]
Just backported an upstream PR to fix saving file state (including e.g. resume point).

**Comment by CurlyMoo** [comment]
I believe all is working well.
