### ISSUE TITLE
Btrfs filesystem is broken

### ISSUE THREAD

**Issue by raspi1** [xbianonpi/xbian#643]
Hi,

Somhow, my usb btrfs boot partition /dev/sdb2 became broken. There is no more possible to boot xbian from it. 
I tried to repair it using btrfsck tools (tried different versions 3.16.1, 3.16.2, 3.17.1) but they said there is no possible recover. 
(root 1351 inode 487600 errors 1000, some csum missing
extent-tree.c:2330: __free_extent: Assertion `owner_objectid != btrfs_tree_block_level(leaf, bi)` failed.
btrfs check[0x8077a09]
btrfs check[0x8077a3a]
btrfs check[0x8079ce6]
btrfs check[0x807ab1d]
btrfs check[0x8078170]
btrfs check[0x807006d]
btrfs check[0x80702c6]
btrfs check[0x807215f]
btrfs check[0x804dc9b]
btrfs check[0x8065d02]
btrfs check[0x804e3a6]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0xb746aa83]
btrfs check[0x804e3cc]
)

On a external linux pc I'm still able to mount the btrfs partition.

My question is how to recreate that disk and what to save from the volumes root, modules home, data ??

Thanks

**Comment by f1vefour** [comment]
Closing, old issue that is no longer relevant.
