### ISSUE TITLE
xbian-update obliterates dhclient.conf

### ISSUE THREAD

**Issue by palswim** [xbianonpi/xbian#657]
Whenever `xbian-update` has an update, I lose all of the data in `/etc/dhcp/dhclient.conf` configuration file, save for three lines:
> initial-interval 1;
> reboot 4;
> script "/etc/xbian-udhcpc/dhclient-script-xbian";

Thankfully, I had the initial `dhclient.conf` from the base XBian (1.0r2) image from which to restore the configuration, but I have to restore that backup each time `xbian-update` updates.

**Comment by mk01** [comment]
can you try 
```
touch /run/noreboot
wget http://download.serveftp.net/other/xbian-update20150114-0.deb
dpkg -i xbian-update20150114-0.deb
 ```

**Comment by palswim** [comment]
A diff confirms that I have an identical `/etc/dhcp/dhclient.conf` file to the file I had before the update. Thanks!
