### ISSUE TITLE
auto login

### ISSUE THREAD

**Issue by tvideovi** [xbianonpi/xbian#664]
I need to auto login to the system, i.e. no login/pw on boot but rather the ability to run a script or autostart terminal.

Is this possible in xbian?

Curlymo suggested some links (thank you very much) but they did not work. Tried many advised changes to various files but all changes reverted back to unchanged after re boot.

I could see this as interesting to others so I thought I would ask here.

**Comment by CurlyMoo** [comment]
Can you ask first on the forum so we are sure it isn't a bug.

**Comment by tvideovi** [comment]
Hi Curlymo.

Of course, pls remove this, sry.
