### ISSUE TITLE
PAPlayer playing FLACs makes only white noise (ALSA)

### ISSUE THREAD

**Issue by 0xFACE** [xbianonpi/xbian#671]
After latest upgrade PAPlayer playing FLACs makes only white noise. 
I use xbian-package-xbmc-alsa package with I2S DAC for audio.
Before it worked well. 
There is no problem with the ALSA subsystem - mplayer works without problem.

**Comment by CurlyMoo** [comment]
Why are you still using the xbmc alsa package when we switched to Kodi with alsa support by default?

**Comment by 0xFACE** [comment]
Because I have not noticed that you are using now Kodi with ALSA support.
Checked new Kodi with ALSA, no issues  so fare.
