### ISSUE TITLE
kernel_3.17.7-ck2+-1424092457 system freeze for 1 hour every half hour

### ISSUE THREAD

**Issue by Fabio72** [xbianonpi/xbian#678]
since upgrade to kernel xbian-package-kernel_3.17.7-ck2+-1424092457 my system show the following behaviour
http://forum.xbian.org/thread-2703.html
After an uptime of 30m sistem freeze for 1 hour then reboot.
https://www.dropbox.com/s/n5wr5n8lomavvwr/14-day.png?dl=0
Around 18:00 I made some forced reboot and disconnection from PSU

After downgrading to 3.17.7-ck2+-1421550584 everything is fine again

**Comment by CurlyMoo** [comment]
I've removed that specific kernel from the repository. Thanks for reporting.
