### ISSUE TITLE
autofs spams /var/log/upstart/autofs.log

### ISSUE THREAD

**Issue by mkreisl** [xbianonpi/xbian#683]
I'm using autofs to access my remote video library. 

A few days ago i found, that the logfile /var/log/upstart/autofs.log grows extremely on my 24/7 running Pi. 
Removing the -v -d start option in /etc/init/autofs.conf solves the issue only temporarely, because after each running an update (package xbian-update) my modification has gone. 
I think it would be better to put these options into /etc/default/autofs variable OPTION so everybody who likes to have log-spam can enable this

**Comment by CurlyMoo** [comment]
Can you make a pull request with these changes?

**Comment by mkreisl** [comment]
Yes, will do it tomorrow
