### ISSUE TITLE
Error running nightly 21/2 on raspberry pi 1 (512mb)

### ISSUE THREAD

**Issue by chrisofthewhites** [xbianonpi/xbian#688]
Hi,
I never seem to get a trouble free update :-(
The error this time happens when booting, works first time but that's all.
All i see on screen is:
[693]: timeout: killing '/sbin/modprobe -b usb:v7392p7811d0200dc00dsc00dp00icFFiscFFipFFin00' [745]

The pi goes into an infinite loop displaying this message

Anybody any ideas?

EDIT: The PI starts USB hub isn't connected, and after a while the wireless network stops working when I plug it in after it has started. So thinking a problem with the wireless usb, which was working fine up untill the update

EDIT: noticed that the wifi adapter has a little chip out of it, so it was physically damaged. New one on the way, apologies for the unnecessary post!

**Comment by f1vefour** [comment]
No worries, thanks for closing.
