### ISSUE TITLE
CEC fails in Kodi

### ISSUE THREAD

**Issue by ggggh** [xbianonpi/xbian#692]
During the last week (after one of the recent updates) CEC stops working after a while.  Interestingly, it seems to happen much sooner if overclock is on None (where it just stops working while you are using it).  If overclock is on Xbian standard setting, it seems to fail only after rpi has been idle for some time.

**Comment by f1vefour** [comment]
Going to need Kodi and dmesg logs, please post them to pastebin and link here.

**Comment by CurlyMoo** [comment]
I though he meant Jidi, but it was Kodi ;)

**Comment by mkreisl** [comment]
Same happens here :-(

I' will turn on logs and post them after this issue happens again

**Comment by mk01** [comment]
@mkreisl 

don't forget that the usual DEBUG logging is not enough. since KODI, specific subsystem must be set for DEBUG logging too (CEC in that case).

somewhere under settings->system->debug-> .....

**Comment by mkreisl** [comment]
@mk01
thanks for the tip, I have now enabled CEC messages too and now waiting for the issue, which happens very seldom: 2x I remember and 1x directly after start, but unfortunately no logs preserved because I currently investigate an other issue (it's too early to talk about this)

**Comment by ggggh** [comment]
Sorry I haven't come back with more info, but after a week where this was happening all the time, this is now not happening anymore.  Separate issues (such as inabillity to update kernel without rpi freezing) led me to believe it was a power problem under load.

**Comment by f1vefour** [comment]
@ggggh Did you change supplies and the issue went away?

**Comment by ggggh** [comment]
No, didn't change it - have a new one on order, 
Rpi seemed mostly ok for a few days...until I met a frozen rpi when I arrived yesterday.
Only other issue is that it still seems to freeze whenever the upgrade script tries to update the kernel package - and that's been happening for about a month.
I'm hoping that the CEC issue was fixed by one of the packages that did upgrade.
