### ISSUE TITLE
[IMX] latest image .gz file contains RPI image

### ISSUE THREAD

**Issue by zilexa** [xbianonpi/xbian#696]
This is the file I get when I extract http://sourceforge.net/projects/xbian/files/release/XBian_Latest_imx6.img.gz/download:

XBian_2015.03.07_rpi

**Comment by zilexa** [comment]
The link: http://sourceforge.net/projects/xbian/files/release/XBian_2015.03.07_imx6.img.gz/download
Does contain the IMX image. It is just the "Latest IMX" image that has the wrong file. Simple mistake.

**Comment by zilexa** [comment]
FYI This image (not using the 'latest' link) DOES work (the image from last week does not boot).

**Comment by CurlyMoo** [comment]
Fixed.
