### ISSUE TITLE
Can´t save "Spin Down HDD" Option in Kodi Xbian-config

### ISSUE THREAD

**Issue by stangl** [xbianonpi/xbian#699]
Hi,
i can´t save the "Spin Down HDD" option in Kodi Xbian-config.
If I enable this option, it asks me to save the option. If i say yes and come back later the option is disabled again??!!

all current system updates are done....
is this a xbian bug or could it be, that my external 2.5" HDD doesnt support spin-down and xbian-config checks this before it saves the option?

bye

Edit: ok it's a bug in Kodi xbian Config. If i enable the spin hdd down option nothing Happens. I have to edit the /etc/usbmount/usbmount.cfg file. There is still "spindown=0". If i set it to e.g. Spindown=5 it works and Even the Option is enabled in xbian Kodi config and it Shows an Option to Change the Minutes. Please fix this bug. Thx!

**Comment by mk01** [comment]
@stangl 

nice research. thanks!
we will fix ...

**Comment by CurlyMoo** [comment]
@anaconda was correcting this.
