### ISSUE TITLE
udev permission denied errors on boot

### ISSUE THREAD

**Issue by Fabio72** [xbianonpi/xbian#700]
Distribution: XBian 1.0 (knockout)
Kodi: 14.2-RC1 Git:Unknown
Kernel version: Linux 3.18.8+ armv6l
Firmware: 115f63aa0915cdb5b6dff23822eb16699b72ae8b (4 Feb 2015 21:04:27)
PI version B+

I'm getting two error messages at boot. They are very quick so I had to make a video to see something
udev error opening /sys/devices/platform/mmc-bcm2835.0/mmc_host/mmc0/mmc0:59b4/block/mmcblk0/queue/iosched/slice_idle
and
udev error opening /sys/devices/platform/mmc-bcm2835.0/mmc_host/mmc0/mmc0:59b4/block/mmcblk0/queue/iosched/target_latency
both for permission denied.

/sys/devices/platform/mmc-bcm2835.0/mmc_host/mmc0/mmc0:59b4/block/mmcblk0/queue/iosched is empty after boot
Everything else is working fine, so maybe is only a cosmetic problem.

**Comment by mk01** [comment]
@CurlyMoo @f1vefour @anaconda 

guys, can any of you confirm that ? 

@Fabio72 

empty (non existing) queue/iosched is definitely not good ;)

**Comment by CurlyMoo** [comment]
I saw them sometimes but can't remember when...

**Comment by anaconda** [comment]
10-local-xbian.rules has:
```
ACTION=="add|change", KERNEL=="mmcblk0", ATTR{queue/iosched/slice_idle}="0"
ACTION=="add|change", KERNEL=="mmcblk0", ATTR{queue/iosched/target_latency}="120"
```

`slice_idle` here is 0, but I don't have a `target_latency`:
```
$ sudo cat /sys/devices/platform/mmc-bcm2835.0/mmc_host/mmc0/mmc0\:0007/block/mmcblk0/queue/iosched/target_latency
cat: /sys/devices/platform/mmc-bcm2835.0/mmc_host/mmc0/mmc0:0007/block/mmcblk0/queue/iosched/target_latency: No such file or directory
```

`iosched` is not empty here, but this a Pi 2 (3.18.8+).

**Comment by Fabio72** [comment]
https://plus.google.com/118154946688569975412/posts/ertVfXjJxvE

I have too

**Comment by Fabio72** [comment]
Maybe I solved!
I found scheduler=noop on my cmdline.txt. I don't kown why, maybe it comes from where I copied the configuration for nfs root.
I must wait to go home to double check but after changing scheduler on the fly queue/iosched is not empty any more
