### ISSUE TITLE
Can't configure CEC anymore

### ISSUE THREAD

**Issue by RolfTimmerman** [xbianonpi/xbian#705]
Recently I've installed a fresh copy of XBian (20150304-2) and everytime I start my TV, it automatically switches back to XBian (once or twice) which is quite annoying. Before the update I was able to configure CEC through system settings (under peripherals?) but now there is no such option anymore.

**Comment by bairdy** [comment]
@RolfTimmerman 

What version of kodi is running? is it the latest is 14.2-rc1 (compiled March 13th) as ive just checked and as it does have the option to disable still.

 its located still under from the main home screen
 ```System>Settings>System>Input Devices>Peripherals>CEC Adapter```

**Comment by RolfTimmerman** [comment]
It is the latest. I know where it should be, but it isn't there anymore only a blank Peripherals list.

**Comment by RolfTimmerman** [comment]
Somehow the option is back maybe because ive installed a new kodi version.
