### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by The-Exnor** [xbianonpi/xbian#706]
As requested by f1vefour here is as picture of Kernel panic situation that is recurrent on 2 units (http://forum.xbian.org/thread-2783-page-3.html) and (http://forum.xbian.org/thread-2827.html).

Picture (http://s10.postimg.org/y6r0r3mnd/Kernel.jpg)

Have you any idea @mk01

Thanks.

**Comment by CurlyMoo** [comment]
Please try `compress=lzo` for btrfs and reboot (`/boot/cmdline.txt`)

**Comment by The-Exnor** [comment]
Ok, trying that. will post progress.
Thks

**Comment by The-Exnor** [comment]
@CurlyMoo  : Sorry mate this did not worked... tested on my 2 rPi 1 B and after less than 24h i've still got crashes and one Kernel Panic.

One of the units was freshly installed with the latest Xbian stable, available on the Win installer, then updated via apt-get. No other addons installed, no other configurations. Also OC @ xbian.

Thks.

**Comment by CurlyMoo** [comment]
Can you try a fresh install but before you boot change the btrfs compress to lzo?

**Comment by f1vefour** [comment]
@The-Exnor Please try this updated kernel for RPi 1 and let me know how it goes.

https://db.tt/sNM5ty8M

Install by doing:
```
sudo cp /boot/kernel.img /boot/kernel.good
sudo dpkg -i xbian-package-kernel_3.19.3+_armhf.deb
```

**Comment by The-Exnor** [comment]
@CurlyMoo  and @f1vefour :

Ok so Curly i'm already running a fresh install with btrfs compress level at LZO on both parameters i will post if it crashes

@f1vefour  i'm going to install your Kernel on my other rPi 1 unit and will post the result (btw thank you for compiling that for me :) )

I will post results in here and on Xbian forums

**Comment by CurlyMoo** [comment]
At least it booted here and the scrub succeeded.

**Comment by The-Exnor** [comment]
@CurlyMoo 

Yes scrub does not crash anymore i've tested that too... but last time (after changing the btrfs compression) it also succeeded, and it lasted for several hours until it crashed.

**Comment by f1vefour** [comment]
Thanks for testing, I am hoping we can move past the 3.18 branch and make 3.19 the default. I wish I could have pre-tested beforehand but I'm relatively sure the kernel will boot and function since a lot of Pi specific code has made it into the 3.19.y branch.

**Comment by The-Exnor** [comment]
@f1vefour 
sorry for the noob question but after installation do i need to do anything else besides rebooting?

**Comment by f1vefour** [comment]
Nope, just reboot. If you have still have issues I will help you update the firmware.

**Comment by The-Exnor** [comment]
@f1vefour 
Ok i have it installed and its running fine so far.. it past btrfs scrub without issues... i hope this is the one.
Do you want me to send you any log file or info?

**Comment by f1vefour** [comment]
You could pastebin dmesg and link here so I can make sure nothing is initially wrong, thanks.

**Comment by The-Exnor** [comment]
@f1vefour  here you go mate (attached as .jpg... rename it to .txt :P) 
![dmesg txt](https://cloud.githubusercontent.com/assets/11633345/6882628/f5d1e176-d583-11e4-8350-e89d7df8ba87.jpg)

**Comment by RolfTimmerman** [comment]
Here is mine: http://pastebin.com/CEjQp2BP

**Comment by The-Exnor** [comment]
@RolfTimmerman 
is your running ok now?

**Comment by RolfTimmerman** [comment]
For now but its only running for 5min ;)

**Comment by RolfTimmerman** [comment]
Still running, fingers crossed!

**Comment by The-Exnor** [comment]
Same here... so far so good.

**Comment by The-Exnor** [comment]
@f1vefour 

Well the unit did not crash but kody did and i lost SSH so i had to hard reboot and now i'm stuck on the splash screen saying "init process" ... it does respond to ctrl+alt+del but i cant bypass the splash screen with any of  the key combinations that i've tried.

So i guess i have to re-install and restart the test... any suggestions? 

@CurlyMoo 
The unit running your suggestion is still up and running. Only Kodi crashed but the OS is responsive.

**Comment by The-Exnor** [comment]
@CurlyMoo 
Just noticed one thing... the unit i've freshly installed and applied the LZO setting did not expand the file system... It was installed on a 8GiB card and only less than 400 Mib are used with only 44 MiB available on the system partition.
Also the swap partition was not created.

**Comment by CurlyMoo** [comment]
Are you sure that's related to lzo?

**Comment by The-Exnor** [comment]
@CurlyMoo  Not sure... i did nothing on that unit besides installing fresh, modify the LZO part and boot... this is the 1st time i actually take time to see how it was performing, besides not crashing.

**Comment by The-Exnor** [comment]
@f1vefour 

After a fresh install on a new sdcard, and after installing the new Kernel and about 1 hour of runtime the unit froze again (no messages on screen) and on reboot the 2nd partition (btrfs) was corrupted again :/
No modifications on the system this time besides the installation of the Kernel (used latest stable image and did not performed any update.).
Any suggestions?

**Comment by The-Exnor** [comment]
@CurlyMoo 

Just re-installed a new one with your idea. This time the filesystem/partitions were created normally. 

Used zswap.compressor=lz4 and compress=lzo. Last time i used zswap with lzo.

Lets see if it still holds like the last time, now that the partitions are correct.

**Comment by The-Exnor** [comment]
@CurlyMoo  well scrub this idea mate... few minutes of doing nothing and i've just got Kernel Panic screen again... Is there any file i can post here to help?

**Comment by CurlyMoo** [comment]
So it's not lz4 :smile:

**Comment by The-Exnor** [comment]
@CurlyMoo it appears its not.... but i'm getting out of option here :(  new install crashes, new Kernel makes FS corrupt ... any ideas ??? from the forums i know i'm not the only one with the same problem.

Off topic: why LZ4 ? isn't this setting more compute demanding?

**Comment by CurlyMoo** [comment]
We patch lz4 customly inside the kernel. Somehow it's IO related but i don't know where. I never had issues with normal Kodi + pilight usage.

**Comment by The-Exnor** [comment]
@CurlyMoo  any theories about what is happening in this situations?

**Comment by CurlyMoo** [comment]
Nope, maybe @mk01?

**Comment by RolfTimmerman** [comment]
My RPi crashed again today

**Comment by f1vefour** [comment]
It could be the bfs/bfq patches, the only thing left to try is build a kernel without those patches and see what happens. I think we need to provide a image without lz4 and an unpatched vanilla kernel because this is getting ridiculous.

**Comment by f1vefour** [comment]
I have had no kernel panic on any of the kernels on either the Pi 1 or 2, I can get a freeze when a torrent approaches 5 megabyte/s. But it isn't locked up as if I leave it alone it comes back.

**Comment by The-Exnor** [comment]
@f1vefour  so this is not an isolated case right? More people are getting the same problem for what i can see on the forums and in here.

Was there any major change on the last 2 kernels? because before everything was ok.

Also, now Kodi is very sluggish to respond to commands, either direct from keyboard or android app, and am talking about fresh out of an installation.

**Comment by f1vefour** [comment]
I'm beginning to think it's a hardware issue, since 99% of all users aren't having these problems.

My current best recommendation is to downgrade to 3.17.y or earlier and see if you have the same issue, since this is the kernel you previously had no issue with.

Have you tried other SD cards?

**Comment by CurlyMoo** [comment]
The most radical idea is building a ext4 root image. And that's what i'm doing now. If that is still crashing is has to be a hardware issue.

**Comment by CurlyMoo** [comment]
Can you try this image:
http://download.xbian.org/testing/XBian_2015.03.31_rpi2-test.img.gz

**Comment by The-Exnor** [comment]
@f1vefour yes i'm using 2 rPi 1 units and tried 3 different SDcards betwen them...

@CurlyMoo ok, just one question: this image is just for test or if is stable will i be able to continue to update it?

**Comment by CurlyMoo** [comment]
Just for testing.

**Comment by f1vefour** [comment]
Thanks @CurlyMo, this will definitely help determine the issue.

**Comment by The-Exnor** [comment]
@CurlyMoo @f1vefour 

Thanks, tomorow i will give it a try ASAP. Today i don't have the time.

Ps: the .x.19 kernel just corrupted the 2nd partition for the 4th time today... (and its a different SDcard)

**Comment by f1vefour** [comment]
Is your Pi UK or China made? Because the UK made has Samsung RAM and China is something else, this caused issues before.

**Comment by The-Exnor** [comment]
@f1vefour  i bought it (both actually) from an official seller on the UK (link is directly on the Raspberry pi foundation page).  

Also i bought my 2nd Pi almost a year later than the 1st... and they both have the same problem :/

Just in case, how do identify if my rPi units are UK made or PRC?

**Comment by The-Exnor** [comment]
@f1vefour @CurlyMoo 

Your test img does not boot on any of my rPi... i flash it using Win32DiskImager on 3 different SDcards.

Any suggestions?

**Comment by f1vefour** [comment]
@The-Exnor The Pi on the right is UK made http://i.ytimg.com/vi/qP4qoVnhAEY/maxresdefault.jpg

**Comment by The-Exnor** [comment]
@f1vefour  my oldest unit is made in PRC (black audio input jack) and my less old one (lol) is made on the UK (or at least its said so on the PCB and it has the blue audio jack).

**Comment by f1vefour** [comment]
Good that you have both, that rules out the RAM theory.

What kernel is on the vanilla install?

**Comment by The-Exnor** [comment]
@f1vefour as of today the x.18+ with ZL4 compression.

I'm testing something on one of the units... i got a theory about instability on some OC at the GPU (last year i've tried several setting and got some interesting results...) and i've reverted the clock to the default settings (below the ones on Xbian OC). 
So far this installation (downloaded today with the installer) with Kodi NOT running is still alive...

The other unit is also full updated and so far only Kodi crashes when idle (simple Stop/Start resolves that via SSH). Also this unit i'm using to keep seeing my shows is OC @ Turbo (you can see the pics on the forum, it has 2 active fans for heat dissipation) and never gave any problems like this.

Both units are powered by  2.5 A/h PSU's .

**Comment by Nikamura** [comment]
Is there anything I can help, I have stock xbian on rpi2 with rtorrent running and after leaving it over night running it crashes or just if it uses 100% cpu for some time it also crashes

**Comment by The-Exnor** [comment]
@f1vefour @CurlyMoo 

So my test unit that has kodi stopped, so far did no crash or Panic. (3.18.8+, with all the updates as of yesterday). I notice some "lag" via SSH console that was not there prior to this Kernel, but so far it passed the stress tests i made (reaching 48h without a Panic)

The other unit (where i can still watch a movie) when alone, freezes/crashes Kodi. (so typically i have to kill/start kodi twice a day on this unit).

Can this be an issue with Kodi itself or any of the services supporting it?

**Comment by CurlyMoo** [comment]
Does this test unit run as download box with lots of IO?

**Comment by The-Exnor** [comment]
@CurlyMoo  No... its idling with TOP running... but i did test moving big files over Wlan and it did no crash.

**Comment by CurlyMoo** [comment]
Can you do a IO / CPU stresstest somehow for an extended period of time?

**Comment by The-Exnor** [comment]
Yes... how do you propose i do that? Besides Kodi what else can use the CPU to the max?

**Comment by CurlyMoo** [comment]
I would suggest googling for a nice script...

**Comment by Smultie** [comment]
http://stackoverflow.com/questions/2925606/how-to-create-a-cpu-spike-with-a-bash-command

For example.

So 
fulload() { dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null & }; fulload; read; killall dd
should work

**Comment by The-Exnor** [comment]
@CurlyMoo  just started kodi on that unit and it crashed in less than 5 min.... started slughish then input become even more slow and finally froze...

@Smultie  thnks mate going to try that one... i want to see if this is related to Kodi itself.

**Comment by CurlyMoo** [comment]
The script from @smultie just tests memory IO, not disk IO.

**Comment by Smultie** [comment]
It stresses all cores, which was the goal, right?

**Comment by CurlyMoo** [comment]
The goal is disk io :)

**Comment by Smultie** [comment]
I quote (you) 
Can you do a IO / CPU stresstest somehow for an extended period of time?

It does 50% of that.

Why don't you just post a script to be sure we do the right thing¿?

**Comment by CurlyMoo** [comment]
Because i would have to search for it as well.

**Comment by Smultie** [comment]
Fair enough ;)

**Comment by The-Exnor** [comment]
Found a nice Linux program for that. its called "stress" 

Here is the output of 60 seconds of running. (oh and no crashes since i've stopped Kodi):

stress -v -t 60 -c 1
stress: info: [3357] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: dbug: [3357] using backoff sleep of 3000us
stress: dbug: [3357] setting timeout to 60s
stress: dbug: [3357] --> hogcpu worker 1 [3358] forked
stress: dbug: [3357] <-- worker 3358 signalled normally
stress: info: [3357] successful run completed in 60s

going to try a longer time

**Comment by Smultie** [comment]
Some results from my side:

xbian@xbian ~ $ stress --cpu 4 --io 4 --vm 4 --hdd 4 --timeout 1m 
stress: info: [7602] dispatching hogs: 4 cpu, 4 io, 4 vm, 4 hdd
stress: FAIL: [7602] (416) <-- worker 7617 got signal 9
stress: WARN: [7602] (418) now reaping child worker processes
stress: FAIL: [7602] (416) <-- worker 7605 got signal 9
stress: WARN: [7602] (418) now reaping child worker processes
stress: FAIL: [7602] (452) failed run completed in 7s
xbian@xbian ~ $ stress --cpu 4 --timeout 1m 
stress: info: [7627] dispatching hogs: 4 cpu, 0 io, 0 vm, 0 hdd
stress: info: [7627] successful run completed in 60s
xbian@xbian ~ $ stress --io 4 --timeout 1m 
stress: info: [7659] dispatching hogs: 0 cpu, 4 io, 0 vm, 0 hdd
stress: info: [7659] successful run completed in 60s
xbian@xbian ~ $ stress --vm 4 --timeout 1m 
stress: info: [7876] dispatching hogs: 0 cpu, 0 io, 4 vm, 0 hdd
stress: FAIL: [7876] (416) <-- worker 7879 got signal 9
stress: WARN: [7876] (418) now reaping child worker processes
stress: FAIL: [7876] (416) <-- worker 7880 got signal 9
stress: WARN: [7876] (418) now reaping child worker processes
stress: FAIL: [7876] (452) failed run completed in 2s
xbian@xbian ~ $ stress --hdd 4 --timeout 1m 
stress: info: [7884] dispatching hogs: 0 cpu, 0 io, 0 vm, 4 hdd
stress: info: [7884] successful run completed in 60s
xbian@xbian ~ $ stress --vm 4 --timeout 1m
stress: info: [7920] dispatching hogs: 0 cpu, 0 io, 4 vm, 0 hdd
stress: FAIL: [7920] (416) <-- worker 7924 got signal 9
stress: WARN: [7920] (418) now reaping child worker processes
stress: FAIL: [7920] (452) failed run completed in 18s
xbian@xbian ~ $ stress --vm 3 --timeout 1m
stress: info: [7932] dispatching hogs: 0 cpu, 0 io, 3 vm, 0 hdd
stress: FAIL: [7932] (416) <-- worker 7935 got signal 9
stress: WARN: [7932] (418) now reaping child worker processes
stress: FAIL: [7932] (452) failed run completed in 3s
xbian@xbian ~ $ stress --vm 2 --timeout 1m
stress: info: [7938] dispatching hogs: 0 cpu, 0 io, 2 vm, 0 hdd
stress: info: [7938] successful run completed in 60s


Note that --vm greater than 2 crashes.

**Comment by The-Exnor** [comment]
Well system only crashed when and everytime i use Kodi... any ideas @CurlyMoo @f1vefour  ?

**Comment by CurlyMoo** [comment]
Can you try installing previous versions of Kodi? Preferably 13.2?

**Comment by The-Exnor** [comment]
Ok... you mean XBMC ;) .  i dont think i need to go so far as that... previous to the update that started all this mess everything was fine. But i will try to install 13.2

**Comment by The-Exnor** [comment]
@CurlyMoo 
So i burned an old img i had on backup (xbmc 13) and everything works fine. Does not crash/freeze or Panic (kernel is 3.14 i think ) but its not updatable and almost of the add-on i need are not compatible anymore :/

Now on the same rPi i've tested, again with the other SDcard, and current version available still freezes Kodi after some time. BUT without Kodi running it stays stable now.

Since i've runned all the stress tests i know, can it be some of the services that Kodi uses that are making this happen? 
(note that for this test i used no OC, so ARM @ 700 etc etc...).

**Comment by CurlyMoo** [comment]
And if you downgrade Kodi as i asked before?

**Comment by The-Exnor** [comment]
@CurlyMoo  well i didn't  downgrade from the current img... How do i do that?

**Comment by CurlyMoo** [comment]
Searching is your friend: "Apt downgrade".

**Comment by The-Exnor** [comment]
Done that... i need to know the name of the package to install...

**Comment by CurlyMoo** [comment]
`dpkg --get-selections | grep xbian`

**Comment by bairdy** [comment]
@The-Exnor 

try this ```apt-get install xbian-package-xbmc=14.1-1423177674```

I've had the same issues with the most recent version of kodi over the last week or so, aswell as having CEC not responding properly (taking upto 10 minutes to after switching on the tv or to the pi's source before working) and crashing with both HD/SD content locally or over smb by causing a kernel panic if media has been paused by swapping source on the tv then switching back to kodi or even if kodi has been left idle for half our or so on pause which has perviously been ok till kodi updated had been running for over 4 months and had no issue previously.

I  have now switched back to the older version of kodi above and everything seems to working fine for the last 24 hours no crashes or issues but not 100% sure yet will get back in a day or two, but think it could be an issue with kodi 4.2 doing something strange as i have a clone of the one i use for watching media on another pi running a download server with loads of I/O and quite a bit of cpu usage unpacking rar files and has kodi disabled on start up which has ran solidly with no crashes untill i swapped the pis round and started kodi and disabled the download services on the spare then it crashed and did the same after a few hours.

**Comment by The-Exnor** [comment]
@CurlyMoo  going to try on one of the units

@bairdy  Thks mate, going to try this on the other unit, and yes i notice that the problems appear to have some relation with Kodi. With Kodi turned off the system can handle stress tests and even real big files move over LAN without issues (even on 3.18.8+ Kernel).

My question to @CurlyMoo  and @f1vefour is if its possible that one of the necessary services/programs that are included might be causing the instability.

**Comment by CurlyMoo** [comment]
It still tells me IO is a likely cause. A new version of Kodi might raise the IO more then others?

**Comment by mk01** [comment]
@f1vefour 

tim, can you just try this config ? https://github.com/xbianonpi/xbian-package-kernel/raw/master/extra-files/rpi-3.18.y/.config.try

**Comment by mk01** [comment]
@bairdy 

the "idle" -> "resume" crashing won't be related - this looks as a regression (or new but leading to same problem) in 14.x. After @Smultie was asking I tested on imx6 and have the same against vanilla NFS (debian linux NFS3). for 16 months I remember imx6, this wasn't happening before. 

(actually with my setup / devices I don't remember that even from RPI). only prove it is out of kernel is RPI1 image from Oct/Nov past year with kernel to be tested - that way we exclude two other significant factor - firmware, which, was for sure from 80% rewritten with introducing RPI2. 

raspberry has (and always had) HDMI, CEC, all this code in FW (as blobs).

**Comment by RolfTimmerman** [comment]
A short update from my side. A week ago I installed the 'stable' version of XBian via the download tool. After that I've updated everything except for the kernel (which is now still 3.17.7-ck2+). I haven't had any complete freezes except that Kodi doesn't respond to CEC after a while (and sometimes freezes). But a restart of Kodi fixes that. In the mean time I was able to download and copy stuff around.

Is there anything I can test from my side with this configuration?

**Comment by The-Exnor** [comment]
@CurlyMoo @f1vefour @mk01 @bairdy 

Well the revert to an older Kodi so far is working better... But it still get sluggish sometime (but not as bad as 14.2).

@CurlyMoo  you say it must be related to I/O, but how can it be if i've tested all the possible stress scenarios i can think of and i was unable to reproduce either a crash or Panic... furthermore before the update that started all of this, both my units never had any issues of this type and i do push them hard.
And are you referring to IO from what part? CPU to RAM; SoC to SDcard; IO access to USB controller; Data handling inside the CPU/GPU/logic of the SoC?
I your theory is correct then i have 2 faulty rPi units from different batches... and its quite a coincidence they both got the same problem at the same time with the same software update.

My theory is that  in some part of the updated software an unintentional part the code is creating this scenario. I don't think is Kodi alone because i still got random Panics running BTRFS scrubs (but not all the times i've run it...) with Kodi not running.
But since the day that this situation occurred some other software parts where updated and Raspbian repos and some on Xbian and now Panics are extremely rare and so far only with Kodi running.

This is all very frustrating... Old imgs on xbmc (13.x) run without this issues, but if i stick with that i can't update the software...

I appreciate all the efforts you guys make. Sorry for the rant.

**Comment by CurlyMoo** [comment]
Because of all users reporting issues, (almost) all of them used it as a download box as well.
I for example never had issues, but *just* using XBian for Kodi and have all files on a NFS share. So hardly any disk IO, just some network IO when i watch a movie.

**Comment by The-Exnor** [comment]
@CurlyMoo 

Ok... i also only use Xbian for Kodi alone (i do not use it as a download computer because i want it just to be a HTPC and thats it). I do use it for very high bit rate AVC (.mkv container with average 15Mbits/s AVC file and AAC file with DTS or Dolby audio stream) files and the units never ever (even with the update) crashed during a file play over NFS shares or USB drive.
The crashes/freezes and Panics were all under NO network or USB data transfer situations.

I also transferred an 4GiB file twice from my NAS to both units to test that part (as i referred in a previous post) and no crash or Panic...

When i'm not seeing a movie/series the units stay On doing nothing more than running Kodi at idle.

I wish i could debug this better...

**Comment by The-Exnor** [comment]
@bairdy 
"try this apt-get install xbian-package-xbmc=14.1-1423177674"

Mate thanks for this. i'm now using it for 2 days and no more kernel panics :)  
Kodi still crash and burn sometimes but it restarts automatically (i assume this is the setting on the service(?))  but apart from that the OS is now, as far i can tell, stable.

Note for all that this unit is running with LZO settings and 3.18.8+ Kernel.

@CurlyMoo  @mk01 @f1vefour 

On my other unit i've updated last night (UK time of 22h) and now its stuck at boot loading the X libraries ... Any ideas on this?

**Comment by f1vefour** [comment]
@mk01 I am in the middle of moving and starting a new job, someone else will have to take this on for a while as I have no time. Sorry :(

**Comment by The-Exnor** [comment]
@f1vefour   are you leaving the project?

**Comment by Smultie** [comment]
@The-Exnor "...take this on for a while" .... 

He'll be back ;)

**Comment by The-Exnor** [comment]
@bairdy @CurlyMoo @mk01 @f1vefour 

Unit running xbian-package-xbmc=14.1-1423177674 now running for 3 days with ZERO Linux crashes/Panics (Kodi other issues still persist but the OS part appears to be gone)(Kernel 13.18.8+, LZO on 2nd partition).

**Comment by f1vefour** [comment]
I'm not leaving, just have to take a bit of time off until things settle.

**Comment by The-Exnor** [comment]
@f1vefour ok mate :)

So far no more Kernel Panics.

**Comment by Smultie** [comment]
Tbh: I'm running the latest packages and haven't seen a kernel panic for ~ a week I think.

**Comment by The-Exnor** [comment]
@CurlyMoo @f1vefour @Smultie @bairdy 

Reporting ZERO panic or crashes from the OS so far. Still using Kodi 14.1. All other parts are updated.

**Comment by The-Exnor** [comment]
@CurlyMoo @f1vefour and everyone else.

Reporting that still no more problems on the OS part... i think you can close this thread.  Thks for all the help guys.

**Comment by RolfTimmerman** [comment]
Again I've updated everything however the only thing that freezes is Kodi but my RPI is still running. I also have a dmesg which you can find here: http://pastebin.com/ntCweJQ6

**Comment by The-Exnor** [comment]
Kodi 14.1 does not freeze on me anymore but its performance is erratic compared to 13 (xbmc).

**Comment by Fabio72** [comment]
For me kodi freezes seeme related to screensaver.
Since I disabled screensaver no more kodi problems.

**Comment by f1vefour** [comment]
What resolved your issue @The-Exnor?

**Comment by The-Exnor** [comment]
@f1vefour  I don't have any conclusive idea...  8 days ago (or was it more?), I've reinstalled both units using LZO compression for the OS partition, disabled some services i don't use (LIRC, Ahvi), reverted Kodi to the one suggested above (14.1.x), fully updated to this day and no more Panics...

I speculate that the problem was never on the 3.18.8+ Kernel but in some process that was running on the background (was not Kodi because as i stated the Panics occurred even with Kodi not running), but since the original problem a lot of software was updated on a regular basis and i can only think that one of the programs/services/whatever that was updated, was in fact the culprit.
Still Kodi is randomly sluggish compared to xbmc... and as of today i'm running 14.2 with the same issues.

@Fabio72  yep removing the screensaver was my 1st action back when i got the 1st few freezes... Kodi does not freeze/crash anymore but its performance is way below the one that xbmc (13) had.
I have random "slowdowns" and sluggish input performance and i cant pin point the source of the problem... True is that it only happens when Kodi is running (system gets slow even on SSH with Kodi on )

**Comment by Fabio72** [comment]
@The-Exnor yes, also for me kodi has some performance issues. Slowdowns or short freezes navigating menus or browsing nfs. Playback is still fine.
The only things I could see on dmesg are
 hrtimer: interrupt took 54000 ns
but happens once a week, not more. And:
Apr  4 09:47:16 xbian kernel: [262645.634151] INFO: rcu_preempt detected stalls on CPUs/tasks: {} (detected by 0, t=21002 jiffies, g=6630648, c=6630647, q=1052)
Apr  4 09:47:16 xbian kernel: [262645.634187] INFO: Stall ended before state dump start
 but happened once

**Comment by The-Exnor** [comment]
@Fabio72 i have the same issues in Kodi but it also affects playback sometimes.... I wish this could be solved.

**Comment by The-Exnor** [comment]
@mk01 @f1vefour 
Reporting Zero Panics... Kodi 14.2 is still less responsive than xbmc 13.x (now i can't playback x264 above 5Mbits/s rate without random stop-resume, either via CIFS/NFS or USB drive.. and local cache/buffer is disabled as per default) plus still some random input lag..

**Comment by mk01** [comment]
@The-Exnor 

me not having RPI for months so I have no real idea about it's - basically anything. 
But I sent my wife to buy one today (rpi2).

but you speaks about RPI1, right ? the I take both .

**Comment by The-Exnor** [comment]
@mk01  yep model 1 B... i'm having this problem since the 14.1.x version of Kodi (right after the Kernel Panics ceased to exist).

This happens on 2 units totally updated, one running BTRFS with LZO the other LZ4.
Note that before Kodi (14.0.x) i was able to play files with 15Mbits/s rate AVC and DTS without any issues over LAN + smb shares

**Comment by RolfTimmerman** [comment]
@mk01 Just out of curiosity, you don't have RPI's but you do develop XBian? How do you do that?

**Comment by CurlyMoo** [comment]
By having Hummingboards and CuBox-i's.
Several XBian crew members use the SolidRun devices, several the Raspberry Pi's.

**Comment by mk01** [comment]
@The-Exnor 

I remember RPI is playing 40Mbps x264 videos (via Lan) and no cache.
I will look into it once I get RPI again - later today/this week. 

(regardless to any of this discussions - always keep in mind v13 was literally stripped down to basics to be fast - like internal GUI rendering resolution at minimum, 16bit pixel map processing not native, for sure others - this I just want to say "outofthebox" v13 image will always be different than "outofthebox" v14 image).

((but there must be no lag, no stop/resume, hiccups, and others). you use all packages as they are on stable ?))

**Comment by The-Exnor** [comment]
@CurlyMoo  yes all latest stable updates from Xbian repos (i dont even have the nightlies on the configuration... its a pure Xbian image install with updates via apt-get).

I also remember been able to perfectly play a Blu-ray rip file with 30Mbits/s AVC video over the LAN without any issues whatsoever (plus Dolby 5.1 sound). And i did not change any configurations on Kodi. The problem only arrived after v14.0.x (version 14.0 RC if i recall correctly was doing just fine as previous ones). From version 14.1 and upwards Kodi is suffering from hiccups and stop/resume issues (randomly.. i can't find a reason for it.. Kodi get 100% cpu time and everything stops for a few seconds).

The problem is apparently directly connected to Kodi itself, because with Kodi turned off the system can handle a lot of "hard work" with no issues (see above entries about stress tests and real situation of high I/O and CPU usage).

Since for what i can read at the forums i'm not the only one with this issues (especially the input lag), did you guys (devs) changed any part of the code in Kodi that can cause this? 
Or is Kodi more resource demanding than v13.2 (xbmc)?
Do you think is time to upgrade to a rPi model 2?

Thks.

**Comment by mk01** [comment]
@The-Exnor 

the decoding/rendering in 14 was/is quiet broken. I'm 3 per week back-porting code from v15.
Currently it is only in imx6 branch but seeing the extend - best would be do the same for rpi. 

But best to do it is merge branches. I will try to merge rpi into imx6 and then rebuild it as rpi. Maybe in a week.

**Comment by The-Exnor** [comment]
@mk01  oh that explains a lot... why did the Kodi team modified the decoding and rendering algorithms  ? Any reason? 
I hope you can re-instate the code and get back the old performance :)

**Comment by RolfTimmerman** [comment]
I don't know what you guys did but after installing yesterdays updates it runs super smooth again and also CEC is working. Fingers crossed!

**Comment by The-Exnor** [comment]
Testing them... will give feedback

@RolfTimmerman  what rPi version are you using? 1 or 2?

**Comment by RolfTimmerman** [comment]
RPI model 1B

**Comment by The-Exnor** [comment]
@RolfTimmerman  still have some input lag issues... and video decoding performance is still as bad as it was :(

**Comment by The-Exnor** [comment]
@CurlyMoo  in the decoding part here is a photo of when the OMX players stops to what apears to be to compute the sound file (?)
![dscf2175](https://cloud.githubusercontent.com/assets/11633345/7392723/845c8278-ee81-11e4-949e-e02ec0861778.JPG)

**Comment by CurlyMoo** [comment]
Seems to be a buffering issue. Have you tried tuning that?

**Comment by The-Exnor** [comment]
@CurlyMoo  No.. never modified the values that are there by default on the config file. This happens on the 2 units and did not happened back in the 13.2 version (or in the 14.0 as i recall).

Note that this happens on USB drive files too. I even tried with a file on the SDcard and got the same issue. All x264 files above 4 or 5 Mbit/s rate on the video part do this.

**Comment by RolfTimmerman** [comment]
@The-Exnor I will test this evening after I get home to see how Kodi responds. Sonarr, Couchpotato, NzbGet and OpenVPN are all really fast.

**Comment by RolfTimmerman** [comment]
Still the same issues unfortunately :(

**Comment by f1vefour** [comment]
@The-Exnor Could you post the contents of your advancedsettings.xml?

**Comment by The-Exnor** [comment]
@f1vefour ok here it is : 

""""
<advancedsettings>
   <network>
        <buffermode>2</buffermode>
        <cachemembuffersize>29030720</cachemembuffersize>
   </network>
   <fanartres>720</fanartres>
   <imageres>540</imageres>
   <gputempcommand>echo "$(/opt/vc/bin/vcgencmd measure_temp | grep -o "[0-9]\{2\}") C"</gputempcommand>
   <cputempcommand>echo "$(/opt/vc/bin/vcgencmd measure_temp | grep -o "[0-9]\{2\}") C"</cputempcommand>
   <lookandfeel>
        <webserver>true</webserver>
        <guires>720</guires>
   </lookandfeel>
   <bginfoloadermaxthreads>5</bginfoloadermaxthreads>
   <video>
     <adjustrefreshrate>
       <override>
         <fps>23.976</fps>
         <refresh>24.0</refresh>
       </override>
     </adjustrefreshrate>
   </video>
    <gui>
    </gui>
    <gui>


        <visualizedirtyregions>false</visualizedirtyregions>
    </gui>
    <destroywindowcontrols>0</destroywindowcontrols>
    <useddsfanart>0</useddsfanart>
</advancedsettings>
""""

**Comment by CurlyMoo** [comment]
Please read about `github markdown` to properly format posts.

**Comment by The-Exnor** [comment]
@CurlyMoo and @f1vefour  posted img with the code...

**Comment by f1vefour** [comment]
For a test try changing the buffermode to 3 and restarting kodi (test for issue), then 1 and restart kodi (test for issue). Probably won't help but will help rule out buffering being the cause.

**Comment by The-Exnor** [comment]
@f1vefour  Done and done.. no difference...  I don't like mode 1.. it buffers LAN shares too :/ 

I also tried mode 3 (no buffer) and zero differences. The random stop-and-resume are still here on high bit rate files.

**Comment by The-Exnor** [comment]
@CurlyMoo @f1vefour 

my new advancedsettings.xml is

![nano_advc](https://cloud.githubusercontent.com/assets/11633345/7443385/11a1995c-f13e-11e4-84ae-13493d627fa4.jpg)

And like i've said in the previous post now only have problems with above 15Mbit/s rate video...

![vv](https://cloud.githubusercontent.com/assets/11633345/7443391/b0bf766c-f13e-11e4-93ac-e098692969f5.jpg)

**Comment by The-Exnor** [comment]
@CurlyMoo @mk01 @f1vefour   Any input?
