### ISSUE TITLE
[Not really Xbian related, but don't know where else to ask]Multiple daily email from "Anacron job 'cron.daily' on xbian" 

### ISSUE THREAD

**Issue by Smultie** [xbianonpi/xbian#713]
Ever since installing sstmp on my xbian-box (needed it to get emails from SickRage) I get multiple e-mails per day stating that:
"Delivery to the following recipient failed permanently:

     postmaster@10.0.1.5

Technical details of permanent failure:
The recipient server did not accept our requests to connect. Learn more at http://support.google.com/mail/bin/answer.py?answer=7720
[(0) 10.0.1.5 [10.0.1.5]:25: socket error]"

Any Linux-guru that knows how to prevent these?

**Comment by CurlyMoo** [comment]
Because it isn't i'll close it. Please post it on the forum.
