### ISSUE TITLE
abnormally high load average without high process

### ISSUE THREAD

**Issue by Fabio72** [xbianonpi/xbian#714]
I'm getting wrong load average even if no process is sucking cpu cicles
root@xbian ~ # uname -a
Linux xbian 3.18.8+ #1 PREEMPT Thu Mar 5 03:43:34 CET 2015
root@xbian ~ # vcgencmd version
Feb  4 2015 21:04:27 
Copyright (c) 2012 Broadcom
version 115f63aa0915cdb5b6dff23822eb16699b72ae8b (clean) (release

top - 22:13:39 up 1 day,  3:47,  1 user,  load average: 8,05, 7,56, 6,85
Tasks:  73 total,   1 running,  72 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,7 us,  0,3 sy,  0,3 ni, 98,7 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem:    366012 total,   280100 used,    85912 free,      512 buffers
KiB Swap:   501756 total,        0 used,   501756 free,   176104 cached

  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND                                                                                                        
17577 root       7   0  4636 2460 2108 R   0,7  0,7   0:00.08 top                                                                                                            
 1337 xbian     42   0  436m  86m  38m S   0,3 24,3  19:09.20 kodi.bin                                                                                                       
11552 root       1   0     0    0    0 S   0,3  0,0   0:00.57 kworker/u2:0                                                                                                   
    1 root       1   0  3620 2924 2128 S   0,0  0,8   0:04.45 init

**Comment by mk01** [comment]
https://github.com/xbianonpi/xbian/issues/718
