### ISSUE TITLE
No SSA/ASS subtitles displayed with Kodi v15

### ISSUE THREAD

**Issue by mkreisl** [xbianonpi/xbian#722]
It's currently no critical issue, just for notice: 
Kodi 15 uses a new libass call `ass_set_line_position`, which does not exist in the current libass-0.10.0 library coming with debian wheezy.
I build a new library 0.10.1 which provides this new call. 
It can be downloaded from here: http://www.mediafire.com/download/ycbp3t2j2etcqdj/libass-0.10.1.tar.xz

**Comment by CurlyMoo** [comment]
@mkreisl, on a sidenote. I see a lot of technical and valueble input from you. Care to join XBian:smiley: in whatever way?

**Comment by mkreisl** [comment]
@CurlyMoo 
Yes, if I can help, why not. We can talk about that

**Comment by CurlyMoo** [comment]
What would you like and what can you do?

**Comment by mkreisl** [comment]
Hmm, that's the question. I already thought about that an unfortunately I still search for the right answer

**Comment by CurlyMoo** [comment]
I'm ofc not going to give you access to everything directly. So if you want to work on the kernel with @mk01, i'll give you access to that. Or if you want to contribute to xbian-package-config-xbmc, i'll give you access to that.

**Comment by Smultie** [comment]
Yeah, would be nice to have a Kodi 15 we can test ;)

**Comment by mkreisl** [comment]
Yes, that's clear, and I don't want that. What I like to do is to help by bringing Kodi 15 on the way - as far as I can see there are a lot of things to do

**Comment by mkreisl** [comment]
@Smultie 
If you want to test Kodi 15 you can download it from this folder:
https://www.mediafire.com/folder/2ngwumkbzw36z/XBian_Packages

**Comment by Smultie** [comment]
Just to be sure; in running raspberry pi 2 with Debian Jessie, will that work?

**Comment by mkreisl** [comment]
Oh, I don't know, probably not. RPi2 and Jessie, from where did you get this?. It sounds very experimental

**Comment by Smultie** [comment]
Did that together with mk01. Works like a charm!

**Comment by noodle94** [comment]
Thanks mkreisl! i installed the libs today and it seems to work!

**Comment by mer2329** [comment]
i have been searching for about 2 days, this fixed my sub woes.
thank you so much.
