### ISSUE TITLE
Cubox not booting

### ISSUE THREAD

**Issue by zilexa** [xbianonpi/xbian#730]
This is a general bug report related to the issues that has plagued every iMX release: the system fails to boot Kodi. Though in the forum http://forum.xbian.org/newreply.php?tid=2607 reports have been made the image from April 25 is the only one that works, but it only works on 2GB sd cards. 

What is needed to move forward and kill this bug? It seems to be preventing Cubox buyers to use XBian. The following issues already contain log files:

**Comment by zilexa** [comment]
Update: testing the latest image (XBian_2015.06.06_imx6) resulted in errors on the TV, no successful boot. Image attached. Also SSH is not possible. 
![imag0449](https://cloud.githubusercontent.com/assets/3430004/8115256/5f7ae4f2-107a-11e5-9a10-3499bd5c5807.jpg)

**Comment by zilexa** [comment]
This is with a Sandisk Ultra microSDHC class 10 with the I mark of UHS on it.

**Comment by zilexa** [comment]
another user reported the specified Sandisk does not work.
A Transcend 8GB microSDHC class 6 does work!! So does micro sd kingston 8gb class 4. 

The Sandisk is 7.39GB, the Transcend is 7.46GB.

**Comment by j4n-co** [comment]
This was driving me crazy! I experienced the exact same issue with my cubox-i pro and a 16GB Sandisk Ultra microSDHC class 10 card. With a Kingston 16GB microSDHC class 10 card, xbian works perfectly. The Sandisk card also fails when I try to copy the kingston card onto it, so I guess if you're on iMX hardware: stay away from the red and grey!
