### ISSUE TITLE
SQL error or missing database

### ISSUE THREAD

**Issue by hackedbellini** [xbianonpi/xbian#735]
I noticed this in my log when watching a tv show yesterday, on the latest `xbian-package-cec` from stanging on rpi2-jessie:

```
ERROR: SQL: SQL error or missing database
                                            Query: INSERT INTO settings (idFile,Deinterlace,ViewMode,ZoomAmount,PixelRatio, VerticalShift, AudioStream,SubtitleStream,SubtitleDelay,SubtitlesOn,Brightness,Contrast,Gamma,VolumeAmplification,AudioDelay,OutputToAllSpeakers,ResumeTime,Sharpness,NoiseReduction,NonLinStretch,PostProcess,ScalingMethod,DeinterlaceMode,StereoMode,StereoInvert) VALUES (5185,1,0,1.000000,1.000000,0.000000,-1,-1,0.000000,1,50.000000,50.000000,20.000000,0.000000,0.000000,0,0,0,0,0,0,0,0.000000,0.000000,0,0,1,73848572,1645210788,1645210324)
```

As a curiosity, I ran `pragma table_info(settings);` on the database, and here is the output:

```
sqlite> pragma table_info(settings);
0|idFile|integer|0||0
1|Deinterlace|bool|0||0
2|ViewMode|integer|0||0
3|ZoomAmount|float|0||0
4|PixelRatio|float|0||0
5|VerticalShift|float|0||0
6|AudioStream|integer|0||0
7|SubtitleStream|integer|0||0
8|SubtitleDelay|float|0||0
9|SubtitlesOn|bool|0||0
10|Brightness|float|0||0
11|Contrast|float|0||0
12|Gamma|float|0||0
13|VolumeAmplification|float|0||0
14|AudioDelay|float|0||0
15|OutputToAllSpeakers|bool|0||0
16|ResumeTime|integer|0||0
17|Crop|bool|0||0
18|CropLeft|integer|0||0
19|CropRight|integer|0||0
20|CropTop|integer|0||0
21|CropBottom|integer|0||0
22|Sharpness|float|0||0
23|NoiseReduction|float|0||0
24|NonLinStretch|bool|0||0
25|PostProcess|bool|0||0
26|ScalingMethod|integer|0||0
27|DeinterlaceMode|integer|0||0
28|StereoMode|integer|0||0
29|StereoInvert|bool|0||0
```

So, it seems that the `Crop*` columns doesn't have values specified on the sql query and from the `pragma table_info` output, they cannot be `NULL`, which made the query fail.

I'm reporting this to you because this was probably something that went wrong when porting something from Isengard. Even if it was from kodi itself, they are not accepting bugfixes for Helix anymore, even the simplest ones, as you can see in [my attempt here](https://github.com/xbmc/xbmc/pull/7169).

**Comment by mk01** [comment]
@hackedbellini 

I'm not big fan of this planning / releasing either - as practically there is completely missing "a stable" release lifecycle.

(before a release gets production stability, it is abandoned, bugs claimed to be fixed only in -next release which is introducing again new bugs. and this repeats already tree releases what I remember)
