### ISSUE TITLE
VNC upgrade not working at all RPi

### ISSUE THREAD

**Issue by coderpop** [xbianonpi/xbian#741]
After todays VNC server upgarde to xbian it is now not possible to start the VNC server from the xbian-config menu on Rpi 2 and no connection is possible via vnc on Rpi 1 model B.

CP

**Comment by mk01** [comment]
there was reissue of ver 2.0.0 (ver 2.0.0fix)

**Comment by coderpop** [comment]
Still not working on Rpi 2. VNC server never starts up. I will check RPi 1 tonight if I get chance.

**Comment by baba420** [comment]
Yes, unfortunately even after the ver 2.0.0fix VNC still doesn work.
(Rpi2, fully up-to-date)

**Comment by coderpop** [comment]
Can anyone tell me how to revert to the old working vnc server please?

**Comment by mkreisl** [comment]
@coderpop 
Not tested because still not needed, for example look here:
http://blog.andrewbeacock.com/2007/03/how-to-install-specific-version-of.html

**Comment by mkreisl** [comment]
New version available, see http://forum.xbian.org/thread-3268-post-34113.html#pid34113

So this issue can be closed now :smile:
