### ISSUE TITLE
Hifiberry digi+ not functioning

### ISSUE THREAD

**Issue by coderpop** [xbianonpi/xbian#752]
2 reports now from people on the forum with RPI2 and Hifiberry digi+ who can't get them to work with the current xbian build.
I can't help test as I don't have a digi+ module.
Anyone able to take a look and see if it can be fixed ?

**Comment by mk01** [comment]
recent kernels for both rpi/rpi2 should have support for it.

but also, as difference to previous kernels (pre 4.1), individual components attached to RPI need use of DTB Overlay files.

here is original RPI documentation https://github.com/xbianonpi/xbian-sources-kernel/blob/rpi-4.1.y/arch/arm/boot/dts/overlays/README
