### ISSUE TITLE
Latest updates breaks I2S support (part 2).

### ISSUE THREAD

**Issue by coderpop** [xbianonpi/xbian#754]
After today's upgrade, I2S support no longer works (again).

I have reverted the file xbian-package-xbmc-scripts=1.2.0 which was needed to get Xbain working with Kodi booting at all.

Now, even though Alsa output is enabled in the system meny, the output is always on HDMI.

Also, the meny display refresh has gone back to 60Hz from 50Hz.

Does any testing happen before these releases?

**Comment by CurlyMoo** [comment]
No, we automatically compile our packages. We offer a multiversion apt repository to fallback to previous version in case of errors and offer snapshot functionality to rollback a system altogether.

**Comment by coderpop** [comment]
Rollback not working and today's 'upgrades' seem to make things worse.

**Comment by mkreisl** [comment]
How did you do the rollback?

**Comment by coderpop** [comment]
http://forum.xbian.org/thread-3087.html

**Comment by mkreisl** [comment]
Ah, interesting. New command for me :smile: 
I'm always using the hard way:
````
sudo mount /dev/root /mnt
cd /mnt/root
sudo mv @ @-bad
sudo mv @-<good-snapshot> @
sudo sync
sudo reboot
````
Never had problems with this commands. And believe me, I use it very often

**Comment by mkreisl** [comment]
I looked into the code of the script, it does the same - only hundreds of more lines of code, works pretty well on my RPi2

**Comment by coderpop** [comment]
Both methods result in a 'file not found' message. Whilst this is off topic, it's annoying !
Now I have no audio and the safe rollback won't rollback!
Thanks for the suggestion though, I know you are trying to help! :)
