### ISSUE TITLE
Graphical glitches in latest version

### ISSUE THREAD

**Issue by renwique** [xbianonpi/xbian#757]
Wiped my SD card and installed 20150817-0, RPi2. I have some weird graphical glitches in Kodi, where text does not show up, or shows with errors. Scrolling through lists/items seems to cause or exacerbate the issue. Screenshots below with yellow rectangles highlighting the problem areas.
![1](https://cloud.githubusercontent.com/assets/2815426/9564923/a116ff98-4e6b-11e5-93db-f69635f087ee.png)
![2](https://cloud.githubusercontent.com/assets/2815426/9564995/dbd0c506-4e6b-11e5-8377-34fffdb61a10.png)

**Comment by renwique** [comment]
Also, upgrading from the included kernel (4.1.4) to 4.1.5 did not fix.

**Comment by mkreisl** [comment]
Maybe modifying some settings may help:
http://kodi.wiki/view/Advancedsettings.xml#algorithmdirtyregions

**Comment by er0l** [comment]
Same issue here. Removing "<visualizedirtyregions>false</visualizedirtyregions>" from advancedsettings.xml makes it better, but still there are some glitches here and there especially when browsing trough long lists.

**Comment by mkreisl** [comment]
I can confirm the issue on a fresh installed img on a RPi2

The solution seems to be:
Update kernel to 4.1.6 and the issue is gone. Just tested

Btw, it does not happen on a RPi1

**Comment by renwique** [comment]
I tried a fresh 20150829 install, which came with 4.1.6, but couldn't get Kodi to start, even with a manual call to ```service xbmc start```. It might have been a bad SD card flash, but I didn't try again.

I tried 20150822 with an ```apt-get upgrade```, updating the kernel from 4.1.5 to 4.1.6. I still have the issue, in almost the exact same places.

**Comment by mkreisl** [comment]
Hmm sounds strange
After I updated the kernel the issue has gone. But I should say, I only tested it on kodi's main screen

**Comment by renwique** [comment]
Playing with ```<algorithmdirtyregions>``` didn't help.
Playing with ```<nofliptimeout>``` caused some interesting problems, including screen the screen going blank after updates if set higher than 6ms.
Setting ```<visualizedirtyregions>true</visualizedirtyregions>``` didn't give me any useful information, other than to see tons of red squares (which I expected). When the red squares faded away, everything was rendered correctly. My guess, of course, is that the entire area is being refreshed as the blocks fade away.

I'm flashing back to my old image from April, and I'm going to see if I can try to replicate the ```<nofliptimeout>``` behavior, and see if the visualized regions look any different.

**Comment by renwique** [comment]
On 20150407-0 running kernel 3.18.8, adding ```<nofliptimeout>1000</nofliptimeout>``` has no effect, the screen updates like normal and continues to display without problem.

On 20150822 with 4.1.6, adding ```<nofliptimeout>``` with a value higher than 6-7 caused screen blanking after the updates happened.

Maybe related? Not sure.

**Comment by renwique** [comment]
Scratch the above, there were two ```<gui>``` stanzas in my config. Behavior between the two are the same; the screen blanks on both versions.

**Comment by renwique** [comment]
Playing with ```<algorithmdirtyregions>``` on the old version didn't cause any problems, except for some slowness on 2, which was to be expected. 1 seems faster than the default (3), so I'm leaving that set.

My only guess is there must be some issue with the graphics code/driver somewhere in the 4.x kernel series. I'm not a developer, so I have no clue where to start with that.

I'm staying on 20150407-0 with 3.18.8 for now. I'd like some of the new features of Isengard, but this is fine for the time being.

**Comment by Smultie** [comment]
I'm having the same issue. Paging @mk01

**Comment by mkreisl** [comment]
We all have the same issue including @mk01. It is absolutely randomly. I already made some tests but at the moment, I can't reproduce it anymore.

**Comment by er0l** [comment]
Leave gui tags in advancedsettings.xml empty and try to open any larger list whether movies or online resources after scrolling few pages moving up and down through the list. it almost always shows up in my setup.

**Comment by mk01** [comment]
@popcornmix

can you please look briefly at this ?
basically it looks it started ~2w ago when I changed our tree to be rebase on top of pop/isengard_rbp_backports (instead of xbmc/Isengard as before). 

before I was merging your newclock4 into our tree. I will double check AGAIN that there are no leftovers in the tree I rebase on top of yours (from previously merging the newclock4, but in-between please take brief look, maybe you will come with an idea what's the issue.

thx

**Comment by mk01** [comment]
ok, found few lines as leftover exactly relevant to rendering / dirty regions.

fixed source, pushed, asked for recompile. rpi2 pkg is already at staging repo, rpi compiling.

@renwique 
it is not unnecessary to re-image always. much faster would be just downgrade installed Kodi package.
available versions can one list via
```
apt-cache policy xbian-package-xbmc
```
and install specific version (15.1~RC1-1438235202 in that example case)
```
apt-get install xbian-package-xbmc=15.1~RC1-1438235202
```

**Comment by mk01** [comment]
rpi package was pushed to staging too

once they would be confirmed as glitch free, they will go stable
