### ISSUE TITLE
XBian_2015.08.29_rpi2.img seems to identify itself as 20150817-0 when running...

### ISSUE THREAD

**Issue by renwique** [xbianonpi/xbian#759]
...in every place I can find, including `/etc/motd`, `/etc/xbian_version` and `xbian-config`. Just a heads up.

**Comment by renwique** [comment]
XBian_2015.08.22_rpi2 also does the same.

**Comment by mkreisl** [comment]
sure, the build procedure is the same
and not changed since month

**Comment by mkreisl** [comment]
only he source has been changed from wheezy to jessie

**Comment by mkreisl** [comment]
the version number comes from xbian-update
