### ISSUE TITLE
Cannot remove usbmount from samba share

### ISSUE THREAD

**Issue by jpataias** [xbianonpi/xbian#760]
Xbian automatically adds my hard drive to the samba shares, however I am no able to remove it or edit the share preferences.

Even with SHARESMB=no, still my hard drive appears in the samba shares.

**Comment by mk01** [comment]
@jpataias 

please confirm later that the 2.0.1 version (originally in staging, now moved to stable) solved the issue.

**Comment by jpataias** [comment]
The problem was fixed with the update. Thanks.
