### ISSUE TITLE
cannot add new smb link in kodi (Rpi 2).

### ISSUE THREAD

**Issue by coderpop** [xbianonpi/xbian#786]
After upgrading yesterday the audio problems were all seemingly fixed.

One thing I cannot now do is add a media link in kodi to a SMB share. Existing shares work fine, but if I try to add a new one in the menu I get as far as the SMB selection but nothing shows after selecting it. No network names appear, just blank box with nothing to select.

**Comment by mkreisl** [comment]
I can
