### ISSUE TITLE
as discussed on IRC retest Composite on RPI

### ISSUE THREAD

**Issue by sdoney** [xbianonpi/xbian#790]
02:02:46  18.624645 T:1837122480  NOTICE: Thread CECAdapter start, auto delete: false
    02:02:46  18.631922 T:1845511088   ERROR: CecLogMessage - RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
    02:02:46  18.632277 T:1845511088   ERROR: CecLogMessage - Open - vc_cec could not be initialised
    02:02:46  18.632437 T:1845511088   ERROR: CecLogMessage - could not open a connection (try 1)
    02:02:46  18.683270 T:1828733872  NOTICE: Thread PeripBusUSBUdev start, auto delete: false
    02:02:46  18.683535 T:1820345264  NOTICE: Thread RemoteControl start, auto delete: false
    02:02:46  19.107546 T:1954787904   ERROR: DBus: Error org.freedesktop.UDisks.Error.Failed - Error mounting: mount exited with exit code 1: helper failed with:
                                                mount: only root can mount /dev/root on /home
    02:02:46  19.126621 T:1954787904  NOTICE: Raspberry PI firmware version: Nov  1 2015 14:49:52
                                                Copyright (c) 2012 Broadcom
                                                version 8f1c8e72174c0415fd479c1c7be66b880fab3d79 (clean) (release)
    02:02:46  19.126879 T:1954787904  NOTICE: ARM mem: 752MB GPU mem: 256MB MPG2:0 WVC1:0
    02:02:46  19.127024 T:1954787904  NOTICE: cacheMemBufferSize: 20MB
    02:02:46  19.127649 T:1954787904  NOTICE: Config:
                                                arm_freq=900
                                                audio_pwm_mode=1
                                                audio_sdm_mod_order=2
                                                config_hdmi_boost=5
                                                disable_commandline_tags=2
                                                disable_l2cache=1
                                                disable_splash=1
                                                emmc_pll_core=1
                                                force_eeprom_read=1
                                                force_pwm_open=1
                                                framebuffer_ignore_alpha=1
                                                framebuffer_swap=1
                                                hdmi_channel_map=8
                                                hdmi_force_cec_address=65535
                                                hdmi_ignore_cec_init=1
                                                initial_turbo=3
                                                over_voltage_avs=0x1b774
                                                pause_burst_frames=1
                                                program_serial_random=1
                                                sdram_freq=450
                                                temp_limit=85
    02:02:46  19.128115 T:1954787904  NOTICE: Config:
                                                device_tree=-
    02:02:47  19.634188 T:1845511088   ERROR: CecLogMessage - RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
    02:02:47  19.634506 T:1845511088   ERROR: CecLogMessage - Open - vc_cec could not be initialised
    02:02:47  19.634674 T:1845511088   ERROR: CecLogMessage - could not open a connection (try 2)
    02:02:47  19.715849 T:1820345264  NOTICE: Thread PeripBusPLATFORMUdev start, auto delete: false
    02:02:47  19.717299 T:1954787904  NOTICE: Register - new video device registered on platform->/sys/class/graphics/fb0: generic_video,hdmi_video (0000:0000)
    02:02:47  19.717535 T:1954787904  NOTICE: InitWindowSystem: Using EGL Implementation: raspberrypi
    02:02:47  19.732178 T:1954787904 WARNING: CalcSAR: Screen SAR - not usable info
    02:02:47  19.732611 T:1954787904 WARNING: UpdateResolutions: ProbeResolutions failed. Trying safe default.
    02:02:47  19.732822 T:1954787904   ERROR: UpdateResolutions: Fatal Error, GetPreferredResolution failed
    02:02:47  19.733177 T:1954787904  NOTICE: Checking resolution 16
    02:02:47  19.776209 T:1954787904  NOTICE: GL_VENDOR = Broadcom
    02:02:47  19.776466 T:1954787904  NOTICE: GL_RENDERER = VideoCore IV HW
    02:02:47  19.776588 T:1954787904  NOTICE: GL_VERSION = OpenGL ES 2.0
    02:02:47  19.776722 T:1954787904  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
    02:02:47  19.776878 T:1954787904  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker
    02:02:48  20.635069 T:1845511088   ERROR: CecLogMessage - RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
    02:02:48  20.635302 T:1845511088   ERROR: CecLogMessage - Open - vc_cec could not be initialised
    02:02:48  20.635427 T:1845511088   ERROR: CecLogMessage - could not open a connection (try 3)
    02:02:48  20.660099 T:1954787904  NOTICE: Running database version Addons19
    02:02:48  20.665403 T:1954787904  NOTICE: Running database version ViewModes6
    02:02:48  20.671829 T:1954787904  NOTICE: Running database version Textures13
    02:02:48  20.690186 T:1954787904  NOTICE: Running database version MyMusic52
    02:02:48  20.716389 T:1954787904  NOTICE: Running database version MyVideos93
    02:02:48  20.723194 T:1954787904  NOTICE: Running database version TV29
    02:02:48  20.728487 T:1954787904  NOTICE: Running database version Epg10
    02:02:48  20.728979 T:1954787904  NOTICE: start dvd mediatype detection
    02:02:48  20.729469 T:1809384368  NOTICE: Thread DetectDVDMedia start, auto delete: false
    02:02:48  20.837620 T:1954787904   ERROR: failed to load requested skin 'skin.confluenceforxbian'
    xbian@xbian ~ $

**Comment by mk01** [comment]
@sdoney 

there was new xbmc package build, please retest
