### ISSUE TITLE
Installer GUI

### ISSUE THREAD

**Issue by Zac610** [xbianonpi/xbian#793]
On xubuntu 14.04, the graphic installer has some GUI glitches:
- installer version is too near the window border
- the downloading textfield is too little for the text inside

here is the screenshot:
![xbian-installer](https://cloud.githubusercontent.com/assets/9107495/11654465/29cb5d78-9da6-11e5-9841-3f55fd9be933.png)

(this is an easy issue ;)

**Comment by bairdy** [comment]
I have a fix to be pushed as well as an update to be able to restore a backed up image. I picked up on it testing restoring images in different Linux distro's and osx.

**Comment by skyway22** [comment]
Also sometimes on ubuntu 14.04, the installer freezes my pc. I only flash from terminal..

**Comment by bairdy** [comment]
@Zac610 ive fixed the GUI and have checked on standard ubuntu 14.04 and on windows you can get a compiled copy from here https://www.dropbox.com/s/bb9lrkdtola81i8/Xbian-Installer-Linux-1.3.zip?dl=0 to try

**Comment by mk01** [comment]
@bairdy 

All is perfect now, even tried running in remote X session running on Mac and proportions / sizes have no single issue (perhaps the only X app running this way I use)

:+1:

**Comment by Zac610** [comment]
Problem solved, great job!

![inst](https://cloud.githubusercontent.com/assets/9107495/14296932/b745283a-fb7c-11e5-9eb4-2e0b9e4bf0ab.png)
