### ISSUE TITLE
Newest update breaks SQL database on Raspberry PI

### ISSUE THREAD

**Issue by LauwS** [xbianonpi/xbian#799]
I thought this was an issue with my PI, so i reinstalled with latest image, created advancedsettings.xml and filled out the same details i always do.
Restarted the PI and everything looked fine.
Saw there was updates in xbian-config, so i installed those.
Rebooted and now all shows and movies are gone.

The model is Raspberry PI B.

**Comment by mkreisl** [comment]
@LauwS 
Which version of *xbian-package-xbmc* are you using? And which repos do you have enabled (stable, staging, devel) ?

**Comment by LauwS** [comment]
Ehm... where / how do i check that?



-------- Oprindelig meddelelse --------
Fra: Manfred Kreisl <notifications@github.com>
Dato: 04/01/2016 18.54 (GMT+01:00)
Til: xbianonpi/xbian <xbian@noreply.github.com>
Cc: "René M. Laursen" <mester_lauw@hotmail.com>
Emne: Re: [xbian] Newest update breaks SQL database on Raspberry PI (#799)


@LauwS<https://github.com/LauwS>
Which version of xbian-package-xbmc are you using? And which repos do you have enabled (stable, staging, devel) ?

-

**Comment by mkreisl** [comment]
Enabled repo's: `cat /etc/apt/sources.list.d/xbian.list`
Installed package: `dpkg-query -l xbian-package-xbmc`

Your mysql server is running?

**Comment by LauwS** [comment]
Enabled repo´s:
deb mirror://apt.xbian.org/mirror.txt      stable  main rpi-jessie
### deb mirror://apt.xbian.org/mirror.txt  staging main rpi-jessie
### deb mirror://apt.xbian.org/mirror.txt  devel   main rpi-jessie

Installed package:
ii  xbian-package-xbmc      15.2-1449270576  armhf            XBMC (rpi/isengard)

And yes the SQL runs, it works on another PI and on my PC :-)

**Comment by LauwS** [comment]
Just did the same on the PI where it works, and it´s the same.
Difference in those 2 PI´s are:
Failing one - Model B Revision 2.0 - Mounting holes
Working one - Model B+

According to http://www.raspberrypi-spy.co.uk/2012/09/checking-your-raspberry-pi-board-version/

**Comment by LauwS** [comment]
Did some more testing... and if i clean install and add a video smb folder and choose TV series, it can fine update library.
As soon as i add my advancedsettings.xml and reboot. Then there is no library and i cannot update the added folder.

**Comment by LauwS** [comment]
Okay, nevermind. It was an mysql issue, had to do a mysqladmin flush-hosts.
Now it works like a charm, as before :+1:
