### ISSUE TITLE
Prompt after some fiddling with pi-hole. BTRFS not working?

### ISSUE THREAD

**Issue by Smultie** [xbianonpi/xbian#800]
I'm running Couchpotato, SickRage, Mysql, Phpmyadmin on my XBian install.
I recently read about pi-hole, and though "well, why not?!" and installed it. Got a couple of errors b/c port 80 was occupied by apache2. Changed apache2 to 8080, installed, but didn't work.
Fiddled some more, got into a stat where I didn't want to be, decided to try to get back to a previous btrfs backup, and got the following:
https://goo.gl/photos/6JtXhhiBCaw8b5d67

What to do?

**Comment by mkreisl** [comment]
@Smultie 
Sorry, for this particular problem I can't help you. I only tried the backup once a long time ago and had similar problems when restoring this backup (or should I say: it did not do what I expected). 

Ususally I use snapshots to restore an older system status (I do this very often), do you know this page? [BTRFS Snapshots](http://wiki.xbian.org/doku.php/snapshots)
