### ISSUE TITLE
XBian often does not boot after a reboot

### ISSUE THREAD

**Issue by Smultie** [xbianonpi/xbian#806]
My XBian install (XBian staging/devel/stable) often does not boot the first time after a reboot.
What steps can I take to find the cause of this failure to boot.

After unplugging and replugging the power connector, it almost always works again.

**Comment by mkreisl** [comment]
@Smultie 
Does the system not properly shutdown or boot?

Maybe you don't wait enough :smile: Sometimes my RPi1 neets up to 3mins until shutdown will be finished

A view into `/var/log/upstart-ev.log` may be useful 

And applying this patch will also log oldstyle SysV processes (got it from @mk01):
```
--- a/etc/init.d/rc
+++ b/etc/init.d/rc
@@ -123,7 +123,9 @@
 			shift
 			scripts="$@"
 			for script in $scripts ; do
+initctl emit -n starting JOB="$script"
 				$debug "$script" $action
+initctl emit -n stopped JOB="$script"
 			done
 		}
 		;;
```

**Comment by Smultie** [comment]
I gave it a "sudo reboot" command through SSH (and VPN)
The Pi never came back online ;)

Guess when I'm back home and (re)plug the power cable, all is fine.

Will look into upstart-ev.log to see if I see anything out of the ordinary.

Thanks for your help thus far!

**Comment by Smultie** [comment]
Anything you can deduct from below?

Mon Jan 25 13:26:16 CET 2016 65042.69 258154.72 stopped mountall                         1.32 0.43 0.26 3/346 27799
Mon Jan 25 13:27:11 CET 2016 65097.73 258366.87 started reboot-force                     0.80 0.47 0.29 6/356 28015
Mon Jan 25 13:27:11 CET 2016 65097.73 258366.87 runlevel                                 0.80 0.47 0.29 4/355 28015
Mon Jan 25 13:27:11 CET 2016 65097.95 258366.95 stopped avahi-daemon                     0.80 0.47 0.29 15/307 28083
Mon Jan 25 13:27:11 CET 2016 65097.95 258366.95 stopped cron                             0.80 0.47 0.29 10/298 28085
Mon Jan 25 13:27:11 CET 2016 65097.97 258366.95 stopped tty2                             0.80 0.47 0.29 13/288 28088
Mon Jan 25 13:27:11 CET 2016 65097.96 258366.95 stopped upstart-file-bridge              0.80 0.47 0.29 14/295 28087
Mon Jan 25 13:27:11 CET 2016 65097.98 258366.95 stopped usbmount-cleaner                 0.80 0.47 0.29 8/280 28091
Mon Jan 25 13:27:11 CET 2016 65097.98 258366.95 stopped udev                             0.80 0.47 0.29 8/276 28091
Mon Jan 25 13:27:11 CET 2016 65097.97 258366.95 stopped xbian-inotifyd-bridge            0.80 0.47 0.29 7/269 28092
Mon Jan 25 13:27:11 CET 2016 65098.00 258366.95 stopped ntp                              0.80 0.47 0.29 4/260 28093
Mon Jan 25 13:27:11 CET 2016 65098.20 258367.08 stopped idmapd                           0.80 0.47 0.29 12/279 28149
Mon Jan 25 13:27:11 CET 2016 65098.20 258367.08 stopped nmbd                             0.80 0.47 0.29 12/276 28149
Mon Jan 25 13:27:12 CET 2016 65098.20 258367.08 stopped lirc                             0.80 0.47 0.29 10/277 28146
Mon Jan 25 13:27:12 CET 2016 65098.20 258367.08 stopped dbus                             0.80 0.47 0.29 15/273 28149
Mon Jan 25 13:27:12 CET 2016 65098.22 258367.08 stopped hwclock.sh                       0.80 0.47 0.29 7/264 28153
Mon Jan 25 13:27:12 CET 2016 65098.20 258367.08 stopped tty1                             0.80 0.47 0.29 5/260 28153
Mon Jan 25 13:27:12 CET 2016 65098.21 258367.08 stopped upstart-udev-bridge              0.80 0.47 0.29 7/260 28154
Mon Jan 25 13:27:12 CET 2016 65098.23 258367.08 stopped frandom                          0.80 0.47 0.29 4/253 28154
Mon Jan 25 13:27:12 CET 2016 65098.25 258367.09 stopped autofs                           0.80 0.47 0.29 4/248 28166
Mon Jan 25 13:27:12 CET 2016 65098.26 258367.09 stopped zram-swap                        0.80 0.47 0.29 3/244 28166
Mon Jan 25 13:27:12 CET 2016 65098.32 258367.17 started wait-for-state  xbmc             0.80 0.47 0.29 4/242 28175
Mon Jan 25 13:27:12 CET 2016 65098.72 258367.79 stopped xbmc-screensaver                 0.80 0.47 0.29 7/241 28202
Mon Jan 25 13:27:12 CET 2016 65098.76 258367.81 started xbian-xbmc-cpufreq               0.80 0.47 0.29 6/239 28210
Mon Jan 25 13:27:12 CET 2016 65098.84 258367.87 started xbmc-priority                    0.80 0.47 0.29 5/246 28233
Mon Jan 25 13:27:12 CET 2016 65099.08 258368.12 stopped xbmc-priority                    0.80 0.47 0.29 4/238 28251
Mon Jan 25 13:27:13 CET 2016 65099.46 258368.90 stopped sickrage                         0.80 0.47 0.29 2/181 28267
Mon Jan 25 13:27:17 CET 2016 65103.61 258384.11 stopping xbmc                            0.74 0.46 0.29 1/140 28292
Mon Jan 25 13:27:17 CET 2016 65103.74 258384.42 starting xbmc-exits                      0.74 0.46 0.29 6/155 28327
Mon Jan 25 13:27:17 CET 2016 65103.74 258384.42 started xbmc-changesettings              0.74 0.46 0.29 7/154 28328
Mon Jan 25 13:27:17 CET 2016 65103.75 258384.42 stopped xbmc                             0.74 0.46 0.29 5/148 28328
Mon Jan 25 13:27:17 CET 2016 65103.82 258384.45 started rc                               0.74 0.46 0.29 6/149 28349
Mon Jan 25 13:27:17 CET 2016 65103.82 258384.45 stopped xbian-xbmc-cpufreq               0.74 0.46 0.29 6/147 28357
Mon Jan 25 13:27:17 CET 2016 65103.85 258384.45 stopped wait-for-state  xbmc             0.74 0.46 0.29 3/142 28358
Mon Jan 25 13:27:17 CET 2016 65103.87 258384.46 stopped openbsd-inetd                    0.74 0.46 0.29 3/139 28366
Mon Jan 25 13:27:17 CET 2016 65103.91 258384.49 stopped xbmc-changesettings              0.74 0.46 0.29 6/141 28382
Mon Jan 25 13:27:17 CET 2016 65103.95 258384.53 started wait-for-state  xbmc-exits       0.74 0.46 0.29 3/144 28399
Mon Jan 25 13:27:17 CET 2016 65103.98 258384.56 stopped tvonoff-xbmc                     0.74 0.46 0.29 4/143 28408
Mon Jan 25 13:27:17 CET 2016 65104.02 258384.61 stopped xbmc-exits                       0.74 0.46 0.29 5/137 28422
Mon Jan 25 13:27:17 CET 2016 65104.05 258384.64 stopped wait-for-state  xbmc-exits       0.74 0.46 0.29 4/139 28439
Mon Jan 25 13:27:18 CET 2016 65104.59 258385.70 started progress-shutdown                0.74 0.46 0.29 2/136 28533
Mon Jan 25 13:27:19 CET 2016 65105.90 258389.31 stopped progress-shutdown                0.74 0.46 0.29 3/131 28578
Mon Jan 25 13:27:19 CET 2016 65106.15 258389.98 splash                                   0.76 0.47 0.29 5/134 28613
Mon Jan 25 13:27:20 CET 2016 65106.49 258390.80 unmounted-remote-filesystems             0.76 0.47 0.29 2/135 28662
Mon Jan 25 13:27:20 CET 2016 65106.51 258390.83 deconfiguring-networking                 0.76 0.47 0.29 1/135 28669
Mon Jan 25 13:27:20 CET 2016 65107.11 258392.57 stopped networking                       0.76 0.47 0.29 3/133 28757
Thu Jan  1 01:00:03 CET 1970 3.36 9.60 starting udev                            0.00 0.00 0.00 8/129 235
Thu Jan  1 01:00:03 CET 1970 3.36 9.60 mounted /run                             0.00 0.00 0.00 9/129 235
Mon Jan 25 13:27:11 CET 2016 3.41 9.64 started upstart-udev-bridge              0.00 0.00 0.00 2/122 254
Mon Jan 25 13:27:11 CET 2016 3.45 9.68 started hwclock.sh                       0.00 0.00 0.00 3/126 268
Mon Jan 25 13:27:11 CET 2016 3.45 9.68 started hwclock-systemd-disable          0.00 0.00 0.00 6/126 269
Mon Jan 25 13:27:11 CET 2016 3.49 9.71 stopped hwclock-systemd-disable          0.00 0.00 0.00 5/119 279
Mon Jan 25 13:27:11 CET 2016 3.57 9.77 started xbmc-failed-start                0.00 0.00 0.00 5/134 315
Mon Jan 25 13:27:11 CET 2016 3.57 9.77 mounted /lib/modules                     0.00 0.00 0.00 6/133 315
Mon Jan 25 13:27:11 CET 2016 3.65 9.83 mounted /home                            0.00 0.00 0.00 4/131 332
Mon Jan 25 13:27:11 CET 2016 3.75 9.85 stopped gssd                             0.00 0.00 0.00 5/131 370
Mon Jan 25 13:27:11 CET 2016 3.75 9.85 started module-init-tools                0.00 0.00 0.00 2/128 371
Mon Jan 25 13:27:11 CET 2016 3.86 9.94 started procps                           0.00 0.00 0.00 6/151 412
Mon Jan 25 13:27:11 CET 2016 3.85 9.94 started failsafe                         0.00 0.00 0.00 5/152 412
Mon Jan 25 13:27:11 CET 2016 3.85 9.94 starting xbmc-preload                    0.00 0.00 0.00 6/151 412
Mon Jan 25 13:27:11 CET 2016 3.86 9.94 started xbian-run                        0.00 0.00 0.00 2/139 413
Mon Jan 25 13:27:11 CET 2016 4.09 10.33 started hostname.sh                      0.00 0.00 0.00 8/145 456
Mon Jan 25 13:27:11 CET 2016 4.09 10.33 stopped module-init-tools                0.00 0.00 0.00 6/145 456
Mon Jan 25 13:27:11 CET 2016 4.09 10.33 stopped procps                           0.00 0.00 0.00 6/145 456
Mon Jan 25 13:27:11 CET 2016 4.13 10.33 stopped hostname.sh                      0.00 0.00 0.00 2/138 466
Mon Jan 25 13:27:11 CET 2016 4.19 10.36 started xbian-inotifyd-bridge            0.00 0.00 0.00 4/139 483
Mon Jan 25 13:27:11 CET 2016 4.26 10.40 net-device-up  lo                        0.00 0.00 0.00 8/143 498
Mon Jan 25 13:27:11 CET 2016 4.28 10.40 autofs                                   0.00 0.00 0.00 3/136 507
Mon Jan 25 13:27:11 CET 2016 4.31 10.41 started autofs                           0.00 0.00 0.00 3/136 514
Mon Jan 25 13:27:11 CET 2016 4.33 10.41 starting network-interface eth0          0.00 0.00 0.00 3/134 522
Mon Jan 25 13:27:12 CET 2016 4.41 10.41 started idmapd                           0.00 0.00 0.00 1/136 548
Mon Jan 25 13:27:12 CET 2016 4.59 10.41 started mountall                         0.00 0.00 0.00 3/151 580
Mon Jan 25 13:27:12 CET 2016 4.72 10.42 mounted /                                0.00 0.00 0.00 13/184 636
Mon Jan 25 13:27:12 CET 2016 4.72 10.42 mounted /lib/modules                     0.00 0.00 0.00 12/184 637
Mon Jan 25 13:27:12 CET 2016 4.74 10.42 mounted /proc                            0.00 0.00 0.00 19/181 639
Mon Jan 25 13:27:12 CET 2016 4.76 10.42 mounted /home                            0.00 0.00 0.00 12/172 647
Mon Jan 25 13:27:12 CET 2016 4.75 10.42 mounted /dev                             0.00 0.00 0.00 13/172 647
Mon Jan 25 13:27:12 CET 2016 4.75 10.42 mounted /sys                             0.00 0.00 0.00 10/169 649
Mon Jan 25 13:27:12 CET 2016 4.73 10.42 mounted /dev/pts                         0.00 0.00 0.00 10/169 649
Mon Jan 25 13:27:12 CET 2016 4.78 10.42 mounted /run/rpc_pipefs                  0.00 0.00 0.00 5/156 651
Mon Jan 25 13:27:12 CET 2016 4.81 10.42 splash                                   0.00 0.00 0.00 7/149 665
Mon Jan 25 13:27:12 CET 2016 4.89 10.42 started openbsd-inetd                    0.00 0.00 0.00 5/149 676
Mon Jan 25 13:27:12 CET 2016 4.91 10.42 stopped xbian-failaccess                 0.00 0.00 0.00 8/150 685
Mon Jan 25 13:27:12 CET 2016 5.10 10.42 mounted /sys/kernel/debug                1.36 0.28 0.09 15/186 757
Mon Jan 25 13:27:12 CET 2016 5.11 10.42 mounted /sys/fs/cgroup                   1.36 0.28 0.09 14/183 762
Mon Jan 25 13:27:12 CET 2016 5.12 10.42 mounted /tmp                             1.36 0.28 0.09 15/182 762
Mon Jan 25 13:27:12 CET 2016 5.14 10.42 mounted /run                             1.36 0.28 0.09 9/175 767
Mon Jan 25 13:27:12 CET 2016 5.16 10.42 started xbian-handle-cursor              1.36 0.28 0.09 17/173 779
Mon Jan 25 13:27:12 CET 2016 5.14 10.42 started mounted-run                      1.36 0.28 0.09 16/173 781
Mon Jan 25 13:27:12 CET 2016 5.22 10.42 started portmap                          1.36 0.28 0.09 13/169 791
Mon Jan 25 13:27:12 CET 2016 5.26 10.43 stopped mounted-run                      1.36 0.28 0.09 6/165 794
Mon Jan 25 13:27:12 CET 2016 5.38 10.45 started dbus                             1.36 0.28 0.09 7/156 812
Mon Jan 25 13:27:13 CET 2016 5.46 10.46 mounted /tmp/autoGrSbaf                  1.36 0.28 0.09 7/157 826
Mon Jan 25 13:27:13 CET 2016 5.48 10.46 started xbian-net                        1.36 0.28 0.09 6/152 827
Mon Jan 25 13:27:13 CET 2016 5.55 10.49 started network-interface lo             1.36 0.28 0.09 11/156 840
Mon Jan 25 13:27:13 CET 2016 5.55 10.49 virtual-filesystems                      1.36 0.28 0.09 4/153 842
Mon Jan 25 13:27:13 CET 2016 5.60 10.51 remote-filesystems                       1.36 0.28 0.09 8/150 849
Mon Jan 25 13:27:13 CET 2016 5.69 10.52 mounted /mnt/movies                      1.36 0.28 0.09 9/158 873
Mon Jan 25 13:27:13 CET 2016 5.70 10.52 mounted /mnt/tvshows                     1.36 0.28 0.09 7/158 875
Mon Jan 25 13:27:13 CET 2016 5.70 10.52 mounted /mnt/download                    1.36 0.28 0.09 5/151 876
Mon Jan 25 13:27:13 CET 2016 5.76 10.53 stopped statd                            1.36 0.28 0.09 7/147 884
Mon Jan 25 13:27:13 CET 2016 5.83 10.57 stopped gssd                             1.36 0.28 0.09 7/153 907
Mon Jan 25 13:27:13 CET 2016 5.84 10.58 stopped portmap                          1.36 0.28 0.09 7/151 909
Mon Jan 25 13:27:14 CET 2016 6.63 11.60 started usbmount-cleaner                 1.36 0.28 0.09 8/149 936
Mon Jan 25 13:27:14 CET 2016 6.69 11.64 started udev                             1.36 0.28 0.09 3/152 949
Mon Jan 25 13:27:14 CET 2016 6.69 11.64 started udevtrigger                      1.36 0.28 0.09 4/148 949
Mon Jan 25 13:27:14 CET 2016 6.87 11.74 started frandom                          1.36 0.28 0.09 5/150 967
Mon Jan 25 13:27:14 CET 2016 7.02 11.79 starting lirc                            1.36 0.28 0.09 15/166 992
Mon Jan 25 13:27:14 CET 2016 7.03 11.79 stopped udevtrigger                      1.36 0.28 0.09 12/165 997
Mon Jan 25 13:27:14 CET 2016 7.35 11.81 started networking                       1.36 0.28 0.09 13/171 1035
Mon Jan 25 13:27:15 CET 2016 7.60 11.83 net-device-added  eth0                   1.36 0.28 0.09 16/179 1057
Mon Jan 25 13:27:15 CET 2016 7.96 11.87 net-device-added  dummy0                 1.36 0.28 0.09 15/177 1099
Mon Jan 25 13:27:15 CET 2016 7.99 11.87 started network-interface dummy0         1.36 0.28 0.09 13/177 1108
Mon Jan 25 13:27:15 CET 2016 8.04 11.87 net-device-added  lo                     1.36 0.28 0.09 9/170 1113
Mon Jan 25 13:27:16 CET 2016 9.03 12.82 started lirc                             1.36 0.28 0.09 3/167 1163
Mon Jan 25 13:27:16 CET 2016 9.16 12.91 mounted /boot                            1.36 0.28 0.09 3/164 1170
Mon Jan 25 13:27:16 CET 2016 9.21 12.94 local-filesystems                        1.36 0.28 0.09 6/166 1179
Mon Jan 25 13:27:16 CET 2016 9.34 13.06 filesystem                               1.36 0.28 0.09 5/171 1210
Mon Jan 25 13:27:17 CET 2016 9.45 13.14 stopped smbd                             1.36 0.28 0.09 9/173 1226
Mon Jan 25 13:27:17 CET 2016 9.46 13.14 xbmc-rc                                  1.36 0.28 0.09 6/170 1228
Mon Jan 25 13:27:17 CET 2016 9.50 13.16 stopped failsafe                         1.36 0.28 0.09 4/166 1236
Mon Jan 25 13:27:17 CET 2016 9.63 13.27 starting xbmc                            1.36 0.28 0.09 12/186 1275
Mon Jan 25 13:27:17 CET 2016 9.64 13.27 started rc-sysinit                       1.36 0.28 0.09 8/185 1274
Mon Jan 25 13:27:17 CET 2016 9.64 13.27 started wait-for-state  xbmc-done        1.36 0.28 0.09 12/180 1275
Mon Jan 25 13:27:17 CET 2016 9.63 13.27 started xbmc-preload                     1.36 0.28 0.09 10/176 1275
Mon Jan 25 13:27:17 CET 2016 9.72 13.28 started avahi-daemon                     1.36 0.28 0.09 8/176 1291
Mon Jan 25 13:27:17 CET 2016 9.74 13.28 started xbian-xbmc-cpufreq               1.36 0.28 0.09 7/174 1293
Mon Jan 25 13:27:17 CET 2016 9.83 13.31 stopped ttyX                             1.36 0.28 0.09 5/172 1317
Mon Jan 25 13:27:17 CET 2016 10.02 13.43 started upstart-file-bridge              1.65 0.36 0.12 5/173 1351
Mon Jan 25 13:27:17 CET 2016 10.19 13.54 started wait-for-state  xbmc-loaded      1.65 0.36 0.12 3/177 1376
Mon Jan 25 13:27:22 CET 2016 15.20 21.25 mounted /mnt/movies                      1.92 0.44 0.14 4/233 1573
Mon Jan 25 13:27:22 CET 2016 15.29 21.29 net-device-up  eth0                      1.92 0.44 0.14 5/237 1593
Mon Jan 25 13:27:22 CET 2016 15.34 21.30 static-network-up                        1.92 0.44 0.14 7/236 1603
Mon Jan 25 13:27:23 CET 2016 15.74 21.73 mounted /sys/fs/cgroup/systemd           1.92 0.44 0.14 2/244 1635
Mon Jan 25 13:27:25 CET 2016 18.07 25.79 started sickrage                         1.92 0.44 0.14 12/287 1830
Mon Jan 25 13:27:25 CET 2016 18.08 25.79 runlevel                                 1.92 0.44 0.14 17/281 1834
Mon Jan 25 13:27:25 CET 2016 18.06 25.79 started setupcon                         1.92 0.44 0.14 13/286 1829
Mon Jan 25 13:27:25 CET 2016 18.15 25.79 stopped rc-sysinit                       1.92 0.44 0.14 9/277 1848
Mon Jan 25 13:27:25 CET 2016 18.25 25.80 started anacron                          1.92 0.44 0.14 17/284 1879
Mon Jan 25 13:27:25 CET 2016 18.24 25.80 started rc                               1.92 0.44 0.14 12/284 1876
Mon Jan 25 13:27:25 CET 2016 18.26 25.80 started cron                             1.92 0.44 0.14 11/283 1883
Mon Jan 25 13:27:25 CET 2016 18.31 25.80 stopped anacron                          1.92 0.44 0.14 9/277 1895
Mon Jan 25 13:27:26 CET 2016 18.42 25.80 stopped setupcon                         1.92 0.44 0.14 7/273 1914
Mon Jan 25 13:27:26 CET 2016 18.46 25.81 mounted /tmp/tmp.8hEeZFa4It              1.92 0.44 0.14 5/273 1929
Mon Jan 25 13:27:26 CET 2016 18.63 25.86 mounted /xbmc-backup                     1.92 0.44 0.14 9/276 1950
Mon Jan 25 13:27:26 CET 2016 18.70 25.86 mounted /run/cgmanager/fs                1.92 0.44 0.14 5/275 1965
Mon Jan 25 13:27:26 CET 2016 18.99 25.99 started xbian-inotifyd-bridge            1.92 0.44 0.14 6/272 1994
Mon Jan 25 13:27:26 CET 2016 19.09 26.02 stopped restore-home                     1.92 0.44 0.14 2/270 2003
Mon Jan 25 13:27:26 CET 2016 19.37 26.45 started nmbd                             1.92 0.44 0.14 1/270 2011
Mon Jan 25 13:27:28 CET 2016 20.64 27.76 started xbmc-loaded                      2.09 0.50 0.16 6/278 2047
Mon Jan 25 13:27:28 CET 2016 20.69 27.77 stopped wait-for-state  xbmc-loaded      2.09 0.50 0.16 6/275 2056
Mon Jan 25 13:27:28 CET 2016 20.79 27.77 started xbmc                             2.09 0.50 0.16 7/290 2083
Mon Jan 25 13:27:28 CET 2016 20.86 27.77 stopped tvonoff-xbmc                     2.09 0.50 0.16 5/290 2092
Mon Jan 25 13:27:33 CET 2016 25.99 29.32 started network-interface eth0           2.24 0.55 0.18 5/278 2125
Mon Jan 25 13:27:35 CET 2016 28.03 30.16 stopped xbmc-loaded                      2.24 0.55 0.18 9/285 2185
Mon Jan 25 13:27:36 CET 2016 28.67 30.17 started xbmc-done                        2.24 0.55 0.18 19/299 2243
Mon Jan 25 13:27:36 CET 2016 28.88 30.17 started ntp                              2.24 0.55 0.18 12/295 2255
Mon Jan 25 13:27:36 CET 2016 28.95 30.17 started screen-cleanup                   2.24 0.55 0.18 12/289 2259
Mon Jan 25 13:27:36 CET 2016 28.88 30.17 started mounted-tmp                      2.24 0.55 0.18 11/291 2258
Mon Jan 25 13:27:36 CET 2016 29.32 30.26 stopped mounted-tmp                      2.24 0.55 0.18 13/285 2278
Mon Jan 25 13:27:36 CET 2016 29.38 30.26 stopped wait-for-state  xbmc-done        2.24 0.55 0.18 12/281 2281
Mon Jan 25 13:27:37 CET 2016 29.42 30.26 stopped screen-cleanup                   2.24 0.55 0.18 7/276 2283
Mon Jan 25 13:27:37 CET 2016 29.80 30.26 stopped xbmc-failed-start                2.24 0.55 0.18 6/278 2300
Mon Jan 25 13:27:39 CET 2016 31.97 30.71 started zram-swap                        2.54 0.64 0.22 4/271 2320

**Comment by mkreisl** [comment]
For me it looks fine
So I would assume the network connection does not work properly
(the mounts in /mnt, are they locally (usb) or network mounts?)

**Comment by Smultie** [comment]
Network mounts.
Could that be the culprit?

It's a NAS that does hibernate, so maybe the mounts weren't reachable?

**Comment by mkreisl** [comment]
Hmmm, but the log says /mnt/movies is ok. And, the NAS should wake up automatically, isn't it?

**Comment by Smultie** [comment]
Yeah, you're right. Any other logs that might give something away?

**Comment by coderpop** [comment]
I have experienced the same issue, but only on Rpi1, not on Rpi2.

I guess you have an Rpi1 Smultie?

**Comment by Smultie** [comment]
Nope, RPi2 :)

**Comment by oxivanisher** [comment]
It seems, that I have the same issue. RPi 2, fresh installed and no network or USB mounts. It "starts" kod, but then it exists without showing the GUI. The kodi log file (debug activated) is very unhelpful why it is exiting. SSH works fine.

**Comment by mk01** [comment]
@Smultie 

apply the commit or edit the file, after deconfiguring network is pretty much done - what comes is just remount rootfs RO and reboot(shutdown).

this we will see only after the edit as @mkreisl told you. then the output will look more like this:
```
Fri Feb 12 01:13:45 CET 2016 13984.20 50289.76 stopped /etc/rc6.d/K04rsyslog            0.50 0.32 0.29 2/130 13444
Fri Feb 12 01:13:45 CET 2016 13984.30 50290.04 stopped /etc/rc6.d/K05umountnfs.sh       0.50 0.32 0.29 2/126 13473
Fri Feb 12 01:13:46 CET 2016 13984.56 50290.97 unmounted-remote-filesystems             0.50 0.32 0.29 3/127 13492
Fri Feb 12 01:13:46 CET 2016 13984.58 50291.00 deconfiguring-networking                 0.50 0.32 0.29 4/127 13499
Fri Feb 12 01:13:46 CET 2016 13984.80 50291.61 stopped networking                       0.50 0.32 0.29 3/130 13572
Fri Feb 12 01:13:46 CET 2016 13984.80 50291.61 stopped /etc/rc6.d/K06umountfs           0.50 0.32 0.29 3/125 13573
Fri Feb 12 01:13:46 CET 2016 13985.27 50293.01 stopped /etc/rc6.d/K07umountroot         0.50 0.32 0.29 3/124 13699
Fri Feb 12 01:13:46 CET 2016 13985.39 50293.31 stopped /etc/rc6.d/K08reboot             0.50 0.32 0.29 2/124 13726
```

**Comment by Smultie** [comment]
Would love to do that @mk01, but I really don't know how!

**Comment by mk01** [comment]
copy this
```
--- a/etc/init.d/rc
+++ b/etc/init.d/rc
@@ -123,7 +123,9 @@
            shift
            scripts="$@"
            for script in $scripts ; do
+initctl emit -n starting JOB="$script"
                $debug "$script" $action
+initctl emit -n stopped JOB="$script"
            done
        }
        ;;
```

ssh into rpi, do:
```
sudo -s
cd /
vi mini.patch[hit enter]
```

then press "i" paste into window. push ESC, release it. put ":w" hit enter, push ESC, release it. put ":q". you should be back in command prompt.
now:
```
patch -p1  < mini.patch
```

should be it

**Comment by mk01** [comment]
also, if you change "splash" into "nosplash" in /boot/cmdline.txt , on start and reboot/shutdown you will see that console log on screen ... (to have idea what is going on)

**Comment by Smultie** [comment]
Hunk #1 FAILED at 123.
1 out of 1 hunk FAILED -- saving rejects to file etc/init.d/rc.rej

Used nano iso vi, but I assume that's all the same for this purpose?!

**Comment by mk01** [comment]
@Smultie 

apparently the change is contained in pool of commits to xbian-update I had in queue (and just pushed).
so in max ~4h there will be xbian-update, just install it (in staging).

**Comment by Smultie** [comment]
Thanks, xbian-update installed. Still need to run the script, or was that
part of the update?

**Comment by mkreisl** [comment]
@Smultie I would assume: NO/YES :smile:

NO --> running script not needed
YES --> is part of the update

This is now in:
```
                        action=$1
                        [ $action = stop ] && uaction=stopped || uaction=started
                        shift
                        scripts="$@"
                        for script in $scripts ; do
                                initctl emit -n $uaction JOB="$script"
                                $debug "$script" $action
                        done
```
