### ISSUE TITLE
cubox: vdr 2.2.0~xbian-1446330623

### ISSUE THREAD

**Issue by didlich** [xbianonpi/xbian#809]
new vdr (old: 2.0.3-3) packages are available in xbian, but it seems they are not working
is someone using the new vdr packages on the cubox?

**Comment by mkreisl** [comment]
What exactly does not work? 
I'm using the vdr 2.2.0~xbian package for RPi2 (this is my PVR backup system :smile:) and works very well there.

**Comment by didlich** [comment]
after installing the packages I tried to start vdr by:
```
sudo start vdr
```
but nothing happens

then I tried to execute the binary by: 
**/usr/bin/vdr**

it it tells me: **illegal instruction**

**Comment by mkreisl** [comment]
Hmmm, sounds not good. Will test it next days on my Hummingboard-Pro

**Comment by didlich** [comment]
ok, it would be fine, if you could give some feedback

**Comment by mkreisl** [comment]
Found the culprit :smile: New packages are online

**Comment by didlich** [comment]
thanks, I'll try it.

**Comment by didlich** [comment]
today I had time to test, it works

I installed also a new set of vdr-plugins, but the vdr-plugin-live is not working
@mkreisl  do you also use the vdr live plugin with vdr vesion 2.2?

**Comment by mkreisl** [comment]
@didlich Currently I'm not using vdr because I was switching to TVheadend some weeks ago. It has better support of the EPG EIT - but IMO timeshift works still better with vdr I used many years before.
Live plugin worked - not all functions - but was ok for me.

**Comment by didlich** [comment]
@mkreisl thanks for your response
while reading the new configuration concept of vdr-2.2 I found finally the problem with vdr-plugin-live, there was a missing symbolic link in /etc/vdr/conf.d for live plugin
so the solution is:
```
cd /etc/vdr/conf.d/
ln -s ../conf.avail/live.conf
```

may be you can fix this in the next build?

**Comment by mkreisl** [comment]
@didlich
Thank you for your response :+1: 
A missing `!` in postinst script was the culprit for some addons not to be autoenabled after installation. Will fix this in the next days
