### ISSUE TITLE
Feature request: rtk8192eu

### ISSUE THREAD

**Issue by djcf** [xbianonpi/xbian#810]
Hi there,

I built a blob for the realtek 8192eu wireless device for latest Xbian 4.1.13+. Is there any interest in including the driver in the distribution? I can submit a PR if so.

https://github.com/djcf/rtl8192eu-xbian

best,

Daniel

**Comment by mk01** [comment]
@djcf 

sure, ... please transform the howto into hook script like this - this way it will be always compiled (and packed) into any kernel package be build.
thanks!

https://github.com/xbianonpi/xbian-package-kernel/blob/master/hooks.d/pre-deb.d/rtl8812au

**Comment by mkreisl** [comment]
@mk01 
Already did this, only have to push my changes :smile:

**Comment by mkreisl** [comment]
@djcf 
New kernel packages are created with included rtl8192eu driver. Could you please test it?
Thanks
