### ISSUE TITLE
Networkserver vs DNS/Nameserver in XBian-config+typo

### ISSUE THREAD

**Issue by Szurgent** [xbianonpi/xbian#817]
Following little bug available in the xbian-config/System/Network/selected interfaces and type=static:

-Status
-SSID
-Type
 -IP Address
 -Network
 -Gateway
 -Networkserver
-Networkserver

1: please add a <space> to the beginning of the last item.
2: Primary DNS and Secondary DNS better than Networkserver and Networkserver

I use raspberry pi 3 with updated preliminari image.

![xbian-config-network](https://cloud.githubusercontent.com/assets/17962963/14124076/0229e616-f604-11e5-8832-bb5c97330acf.jpg)

**Comment by mkreisl** [comment]
Hmmm,  I have **Nameserver** there.
But you're right, a small typo is there

**Comment by mkreisl** [comment]
@Szurgent 
Fixed the column alignment issue. Also the the string "Networkserver" has been changed to "Nameserver", but XBian config does not distinguish between primary and secondary name server.

Btw - you only got the string "Networkserver" if the language which has been selected is not supported

**Comment by Szurgent** [comment]
I see that good in the last release.Thank you.
