### ISSUE TITLE
Screensaver and poweroff hdmi, waking up results in black screen

### ISSUE THREAD

**Issue by Dlinny** [xbianonpi/xbian#82]
XBian Alpha 1.
Monitor connected to raspberry via vga->hdmi converter.
To turn off monitor while screensaver active "tvservice -o" used.
After screenserver exiting to powerup hdmi "tvservice -p" used.
Monitor goes off and on. But screen is black.

While doing this without screen saver (manually in ssh console runing commands) - all fine.

Xbmc is runing. After idle time screensaver again switch off hdmi. Json interface responding. But no picture on screen.
Only way to get xbmc picture back is restarting xmbc (/etc/init.d/xbmc stop / start).

**Comment by x29a** [comment]
Sorry for grave-digging, but this is a popular result. Maybe to bundle these commands is sufficient (instead of xrefresh)? http://raspberrypi.stackexchange.com/a/22046/26266

**Comment by Dlinny** [comment]
@x29a  - I've created https://github.com/Dlinny/script.screensaver.xbian-hdmi-off/tree/x29a branch for you to test this solution, can't test myself due to no access to pi now.

**Comment by mk01** [comment]
@Dlinny 

this is already managed by Kodi itself and configurable from Settings -> System.

**Comment by Dlinny** [comment]
@mk01 
What exactly and where in settings?

**Comment by phylor** [comment]
If you have a black screen on the Pi after `tvservice -p`, following command may help:

    xset dpms force on -display :0
