### ISSUE TITLE
Update Super Repo URL

### ISSUE THREAD

**Issue by NunoFilipeSantos** [xbianonpi/xbian#824]
I am under the impression that the [Super Repo](https://superrepo.org) that comes bundles in Repositories section and File manager has an out of date URL.

The new URL that is [supposed to go there](https://superrepo.org/get-started/) is http://srp.nu.

This is a minor nuisance, since it is easy to change it manually, but having the updated one would be fantastic.

**Comment by mkreisl** [comment]
Don't know where it came from. 
Grepped complete source tree of Kodi, but there is nothing there.
So I would suppose that Kodi fetches those wrong data from somewhere.

**Comment by mkreisl** [comment]
Coincidentally found that place where it is done :smile:

Fix is WIP now

**Comment by mkreisl** [comment]
Fixed
