### ISSUE TITLE
lvm2 uninstallable

### ISSUE THREAD

**Issue by jdeluyck** [xbianonpi/xbian#828]
I'm currently looking to move from raspbian/libreelec to xbian, So I can integrate my custom setup of transmission/sonarr/... and kodi on one box.

When trying to install lvm2 on xbian, it bombs out with 'insserv rejected the script header'.

I didn't debug further immediately, as I'm a bit short on time. Just wanted to drop it here, perhaps there's an easy fix?

**Comment by mkreisl** [comment]
Seems to be this issue: https://github.com/xbianonpi/xbian/issues/818#issuecomment-207845514
There you can find an workaround how to fix it

**Comment by jdeluyck** [comment]
Indeed, that 'worked' - bit of an ugly hack, though.
