### ISSUE TITLE
xbiangit not set

### ISSUE THREAD

**Issue by CGarces** [xbianonpi/xbian#831]
I'm testing the build system of xBian, but i'm doing something wrong

I have cloned the repository and executed `./run.me prepare` with sudo

but   $xbiangit is not set... `echo  $xbiangit` not return anything.

**Comment by mkreisl** [comment]
After first run you have to logout
Did you do this?

**Comment by CGarces** [comment]
Yes, logout and login again

**Comment by mkreisl** [comment]
Hmmm, did this on 4 different machines, was always successful

**Comment by CGarces** [comment]
Strange...
Everithing looks fine

> Writing loader file /etc/profile.d/xbiangit.sh
> Installing 
> Installing done...
> Successfully initialised. Please logout and login again.

How is set xbiangit env variable?

I see 
`export xbiangit=$(pwd)/run.me` at create.buildroot
But nothing more.

**Comment by mkreisl** [comment]
Please look into file `/etc/profile.d/xbiangit.sh`

**Comment by CGarces** [comment]
Fixed, was a weird issue with my path

> $ echo $PATH
> .:.:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

Removing the dots at the beginning fix the issue.
