### ISSUE TITLE
hid-aureal

### ISSUE THREAD

**Issue by pci06** [xbianonpi/xbian#832]
Hi,
could you please add the module hid-aureal in the kernel package ?
Pierre.

**Comment by mkreisl** [comment]
Done.

Please note that yo have to wait up to 4 hours until new built kernel packages are distributed to all mirrors

**Comment by pci06** [comment]
Many thanks.

**Comment by knedlyk** [comment]
I should reopen this report. Please add hid_aureal module for rpi2 kernel package.
