### ISSUE TITLE
Online audio content streaming is poor - audio drops (iMX6)

### ISSUE THREAD

**Issue by Implexus** [xbianonpi/xbian#833]
Hi there,

Probably since you've switched to the RT kernels there is an issue with audio streams in Kodi. It drops audio for a very little time in random intervals (15-60s between each of them) for a few milliseconds. It's really a horrible experience to listen to the music like that.

My device is CuBox-i4 Pro (iMX6-Quad CPU)

Latest kernel working without the mentioned issues was v4.3.3+ (linux-image-armmp=4.3.3+-1458345438).

**Comment by Implexus** [comment]
The issue has been solved by @mk01

**Comment by didlich** [comment]
@Implexus , could you paste the link to the solution please
after last update on my cubox I have the same problem

**Comment by Implexus** [comment]
@didlich This bug-fix should be implemented already. Maybe there is another similar issue with the current release.

**Comment by didlich** [comment]
OK, I'll create a new issue
