### ISSUE TITLE
NOOBS Download is not working

### ISSUE THREAD

**Issue by florian-asche** [xbianonpi/xbian#848]
Hello,

i did try to install the latest version for my rpi3, but the download failed.

**Comment by mkreisl** [comment]
Was just downloading `XBian_by_NOOBS_v2.4_rpi3` with Linux XBian installer, absolutely no problem

**Comment by florian-asche** [comment]
I mean after starting NOOBS and select xbian for installation. That download failed.

**Comment by mkreisl** [comment]
Hmmm, seems you have serious network issues.

Downloaded and flashed NOOBS - runs perfect
Booting NOOBS, downloaded and installed XBian - went absolutely smooth
Starting XBian - works like a charm

**Comment by florian-asche** [comment]
very curious!
ping is ok, speedtest is ok.

**Comment by florian-asche** [comment]
Thanks for all the help. i will close this issue. In case someone else some years later read this, and did have the same issue, your device is maybe broken.
