### ISSUE TITLE
Error when installing crypsetup

### ISSUE THREAD

**Issue by enyecz** [xbianonpi/xbian#855]
Way to reproduce:
1. Take a RP2 (I guess it works with RP3 too, but I don't have one).
2. Install the latest Xbian
3. Boot up, get to the console and try install cryptsetup. You get this:

xbian@xbian ~ $ sudo apt-get install -y cryptsetup

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for xbian: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  cryptsetup-bin
Recommended packages:
  busybox | busybox-static
The following NEW packages will be installed:
  cryptsetup cryptsetup-bin
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 394 kB of archives.
After this operation, 1,377 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main armhf cryptsetup-bin armhf 2:1.7.3-4 [221 kB]
Get:2 http://deb.debian.org/debian stretch/main armhf cryptsetup armhf 2:1.7.3-4 [173 kB]
Fetched 394 kB in 0s (1,189 kB/s)   
Create a snapshot of '/run/btrfs-snap/root/@' in '/run/btrfs-snap/root/@btrfs-auto-snap_apt-run-2017-12-22-1637'
Create a snapshot of '/run/btrfs-snap/root/@btrfs-auto-snap_apt-run-2017-12-22-1637' in '/run/btrfs-snap/root/@last_good_known'
@btrfs-auto-snap_apt-run-2017-12-22-1637, 1 created snapshots, 0 destroyed snapshots, 0 warnings.
Preconfiguring packages ...
Selecting previously unselected package cryptsetup-bin.
(Reading database ... 30355 files and directories currently installed.)
Preparing to unpack .../cryptsetup-bin_2%3a1.7.3-4_armhf.deb ...
Unpacking cryptsetup-bin (2:1.7.3-4) ...
Selecting previously unselected package cryptsetup.
Preparing to unpack .../cryptsetup_2%3a1.7.3-4_armhf.deb ...
Unpacking cryptsetup (2:1.7.3-4) ...
Processing triggers for systemd (232-25+deb9u1) ...
Setting up cryptsetup-bin (2:1.7.3-4) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up cryptsetup (2:1.7.3-4) ...
update-initramfs: deferring update (trigger activated)
initctl: Unknown job: K01nfs-common
insserv: warning: script 'K01nfs-common' missing LSB tags and overrides
initctl: Unknown job: K01nfs-common
initctl: Unknown job: S02dbus
insserv: warning: script 'S02dbus' missing LSB tags and overrides
initctl: Unknown job: S02dbus
initctl: Unknown job: S02dbus
initctl: Unknown job: S02dbus
initctl: Unknown job: K01nfs-common
initctl: Unknown job: S05nfs-common
initctl: Unknown job: S05mountnfs-bootclean.sh
insserv: warning: script 'S05mountnfs-bootclean.sh' missing LSB tags and overrides
initctl: Unknown job: S05checkroot-bootclean.sh
insserv: warning: script 'S05checkroot-bootclean.sh' missing LSB tags and overrides
insserv: Service checkroot has to be enabled to start service cryptdisks-early
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package cryptsetup (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (232-25+deb9u1) ...
Processing triggers for initramfs-tools (0.130-xbian1) ...
update-initramfs: Not updating initramfs.
Errors were encountered while processing:
 cryptsetup
E: Sub-process /usr/bin/dpkg returned an error code (1)

I found some similar bugs, where they are suggesting to [add symlinks](https://github.com/xbianonpi/xbian/issues/818) into /etc/rcS.d, but they do not help. Does anyone have suggestion? Thanks.

**Comment by mkreisl** [comment]
@enyecz 
Similar to all other workarounds:
```
sudo ln -sr /etc/init.d/checkroot.sh /etc/rcS.d/S04checkroot
```
