### ISSUE TITLE
Touchscreen calibration + resolution

### ISSUE THREAD

**Issue by joeyb197** [xbianonpi/xbian#856]
Hey! I recently downloaded Xbian and installed it on my rasperry to put it in my car. The thing is that I cannot find how to calibrate the touch screen and I cannot find how to put the good resolution for my 7' touch screen! Any help would be great!!

Thanks

**Comment by joeyb197** [comment]
![fuck](https://user-images.githubusercontent.com/24771594/34961702-62329e12-fa0e-11e7-9bdd-b8be6e06269a.jpg)

**Comment by mkreisl** [comment]
@joeyb197 That's working for Kodi v17
http://lektiondestages.blogspot.de/2016/06/properly-setting-up-5-hdmi-touchscreen.html

**Comment by joeyb197** [comment]
I'm new in these things, so how can I open the screen where I put commands?

**Comment by joeyb197** [comment]
Oh i'ts not command, how can I find these files then? :/

**Comment by mkreisl** [comment]
and this is good thread also: http://forum.xbian.org/thread-3849-post-33175.html

**Comment by mkreisl** [comment]
/home/xbian/.kodi/userdata

**Comment by joeyb197** [comment]
Yeah, but where do I access these files? how?

**Comment by mkreisl** [comment]
OMG

1) close Kodi and login (user xbian) -- you need keyboard, or
2) ssh into XBian (you need LAN connection)

editor you can use nano

**Comment by mkreisl** [comment]
Unfortunately my touch has bee broken several months ago, so I can not give more help
