### ISSUE TITLE
xbian Mirror 2 is a bust

### ISSUE THREAD

**Issue by delugeduser** [xbianonpi/xbian#860]
http://apt2.xbian.org/ mirror is either hacked or no longer a valid DNS resolve. Either way, this in sources.list will cause problems.

FYI for anyone getting something like this when performing an **apt-get update**:

> 100% [Packages 33.2 MB] [1 InRelease gpgv 5961 B] [Waiting for headers]Splitting up /var/lib/apt/lists/partial/apt.xbian.org_mirroIgn mirror://apt.xbian.org stable InRelease
> E: GPG error: mirror://apt.xbian.org stable InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)

Change _/etc/apt/sources.list.d/xbian.list_ from

`deb mirror://apt.xbian.org/mirror.txt      stable  main    imx6-jessie    armv7l-jessie`

to

`deb http://apt.xbian.org/      stable  main    imx6-jessie    armv7l-jessie`

Should apt2.xbian.org be pulled from the mirrors?

My system: Cubox i4-Pro,
Linux xbian 4.8.15+rt9+ #1 SMP PREEMPT RT Wed Jun 28 18:30:56 CEST 2017 armv7l GNU/Linux

**Comment by f1vefour** [comment]
Thank you for the report, it is a known issue. We have lost contact with the mirror and have been deciding what to do, sorry for the inconvenience.

**Comment by delugeduser** [comment]
No problems. I reported it more for all those who might encounter it and needed a work-around.
