### ISSUE TITLE
Security problem - sudo is needed to start kodi, why ? 

### ISSUE THREAD

**Issue by plumpsack** [xbianonpi/xbian#863]
Hi,

why do I need "sudo" to start kodi ?

I renamed sudo from /usr/bin/sudo and figured out that xbmc/kodi will not start anymore in the gui.

Why?

**Comment by mkreisl** [comment]
It's not a security problem

Kodi is running as user/group xbian, and this is done by sudo, [see here](https://github.com/xbianonpi/xbian-package-xbmc-scripts/blob/master/content/etc/init/xbmc.conf#L74)

If you set the variable DPRIORITY=yes in /etc/default/xbmc, sudo is not used

**Comment by plumpsack** [comment]
ok, i set DPRIORITY=yes into /etc/default/xbmc
but after an reboot I get an xbmc-config-error message on my screen.
?

**Comment by mkreisl** [comment]
Tell me, why do you rename sudo ???

That makes absolutely no sense, `xbian-config` for example (which is started per default if you log in as user xbian) is started via sudo, because root rights are required.

**Comment by mkreisl** [comment]
> And that is exactly the problem.
Which  problem?

> 
> Why does a normal user needs "sudo" to run kodi?
That's the way it is
