### ISSUE TITLE
hid_aureal module for rpi2

### ISSUE THREAD

**Issue by knedlyk** [xbianonpi/xbian#868]
Please add hid_aureal module for rpi2 kernel package. It exists for rpi, but but not for rpi2. 
I didn't find in repositories xbian kernel headers packages for rpi2, why these packages are missed?

**Comment by mkreisl** [comment]
> Please add hid_aureal module for rpi2 kernel package. It exists for rpi, but but not for rpi2.

Will be done tomorrow

> I didn't find in repositories xbian kernel headers packages for rpi2, why these packages are missed?

Packages `linux-headers-bcm2836` and `linux-libc-dev` are available as usual

**Comment by knedlyk** [comment]
Ach, ok, different name of the package. Thanks for the tip, now I can compile module by myself. But it would be good to have it in the official package.

**Comment by knedlyk** [comment]
hid-aureal should be load before usbhid, but it is impossible because usbhid module is built in kernel. It should to be compiled as a module <M>, not as <*>.

**Comment by mkreisl** [comment]
usbhid was **never** built as module

**Comment by knedlyk** [comment]
Yes, my mistake, sorry, I meant hid-generic, CONFIG_HID_GENERIC=m as module.

**Comment by knedlyk** [comment]
Thanks, my remote is working!
