### ISSUE TITLE
Afatech 9015 USB DVB-T driver no longer included

### ISSUE THREAD

**Issue by vondrt4** [xbianonpi/xbian#871]
Hi!
When updating from kernel 4.16 to 4.19, my TV stick stopped working. The modules have probably not been built. I had to rollback to the last SD card backup (Thanks for that feature!). Was that a glitch or is it intentional?

**Comment by mkreisl** [comment]
I can't tell you what happened exactly. That modules was lost with kernel 4.18. No idea why because procedure upgrading to next kernel version is always the same.

Anyway, will enabling this module again for the next next 4.19 kernel release (probably 4.19.70+)

**Comment by mkreisl** [comment]
@vondrt4 
FYI: Kernel 4.19.72+ should have this module included again

**Comment by vondrt4** [comment]
Sorry, but it's still not there. Looked in 4.19.72+, 4.19.75+, and 4.19.80+.

**Comment by mkreisl** [comment]
You're confusing me.

Which module are you missing?
 `dvb-usb-af9015.ko` should be available in kernel packages now, I have checked this

**Comment by vondrt4** [comment]
Yes, that should be it. And it is not present in http://apt.xbian.org/pool/stable/rpi-stretch/x/xbian-package-kernel/ or http://apt.xbian.org/pool/stable/rpi-buster/x/xbian-package-kernel/.

**Comment by vondrt4** [comment]
I have downloaded the kernel sources and your .config and ran "make menuconfig" and it didn't let me select AF9015 until I also selected I2C_MUX, which is listed as dependency. I'll try compiling on the RPi, maybe you'll be faster...

**Comment by mkreisl** [comment]
Sorry, but I can't follow you.

I've downloaded latest kernel for Pi2 (Debian Stretch, stable repo), and looked into: the module is there!

```
(armhfstretch)root@kmcubie:/media/system/ftp/manfred# apt-cache policy linux-image-bcm2836
linux-image-bcm2836:
  Installiert:           (keine)
  Installationskandidat: 4.19.75+-1569331168
  Versionstabelle:
     4.19.75+-1569331168 500
        500 http://kmcubie stable/rpi2-stretch armhf Packages
     4.19.72+-1568320584 500
        500 http://kmcubie stable/rpi2-stretch armhf Packages
     4.19.68+-1566846331 500
        500 http://kmcubie stable/rpi2-stretch armhf Packages
     4.9.108+-1530490703 500
        500 http://kmcubie stable/armv7l-stretch armhf Packages
(armhfstretch)root@kmcubie:/media/system/ftp/manfred# apt-get download linux-image-bcm2836
(armhfstretch)root@kmcubie:/media/system/ftp/manfred# apt-get download linux-image-bcm2836^C
(armhfstretch)root@kmcubie:/media/system/ftp/manfred# ls -la
insgesamt 19028
drwxrwx--- 2 manfred ftp      4096 Okt 28 22:02 .
drwxr-xr-x 5 root    ftp      4096 Okt 28 15:36 ..
-rw-r--r-- 1 root    root 19473564 Sep 24 13:22 linux-image-bcm2836_4.19.75+-1569331168_armhf.deb
(armhfstretch)root@kmcubie:/media/system/ftp/manfred# dpkg-deb -c linux-image-bcm2836_4.19.75+-1569331168_armhf.deb | grep af9015
-rw-r--r-- root/root     41144 2019-09-24 13:19 ./lib/modules/4.19.75+/kernel/drivers/media/usb/dvb-usb-v2/dvb-usb-af9015.ko
```

And you can see, module is in this package

**Comment by vondrt4** [comment]
There seems to be a difference between the RPi and RPi2 versions.
# CONFIG_I2C_MUX is not set for RPi
and
CONFIG_I2C_MUX = m for RPi2

**Comment by mkreisl** [comment]
> There seems to be a difference between the RPi and RPi2 versions.
> `# CONFIG_I2C_MUX is not set for RPi and CONFIG_I2C_MUX = m for RPi2 `

Ok, that could be the reason. I assumed that you are using Pi2 or higher

So, have to fix this for Pi1 as well

**Comment by mkreisl** [comment]
New version 4.19.80 has been built for Pi1 with module for AF9015 included and is available for download in a few minutes

**Comment by vondrt4** [comment]
Hi! My poor Raspberry just finished compiling, but it already has the module loaded thanks to you.

**Comment by mkreisl** [comment]
> Hi! My poor Raspberry just finished compiling, but it already has the module loaded thanks to you.

You're welcome

Yeah, building kernel on a Pi1 is PITA :smile: 
I tried this 6 years ago once, but stopped it after more than 15hrs.
