### ISSUE TITLE
Unable to "Set content" after adding video sources

### ISSUE THREAD

**Issue by morluf** [xbianonpi/xbian#876]
/2020-04-15: edited for clarity

Hi!

I'm having problems on a fresh installation of XBian and thought that you might be able help me here. I was initially going to open a thread on the forums (instead of making a bug report right away), but unfortunately I still don't have thread-posting privileges after creating and activating my account there.

My issue is that I can only choose "Movies" when setting the content type for any given video source. Basically, when I select "TV Shows" or "Music videos" instead, nothing happens.

I've added pictures to illustrate what I mean and I'll go through my process step by step (I apologize for the poor image quality; capturing readable photos off a TV with my crappy smartphone camera is a daunting task):

1. I add my video source (in my case a Samba share on NAS) and make sure that the credentials work.

2. Before I can scan its contents into my library I have to specify the content type [here [img1]](https://user-images.githubusercontent.com/11735768/79287491-41bfcc80-7ec4-11ea-8d9f-25fcfc3eda9a.jpg).

3. Should I at this point select "Movies" as my content type, the behavior is [as expected [img2]](https://user-images.githubusercontent.com/11735768/79287627-b1ce5280-7ec4-11ea-8d35-70f4c0c7f69b.jpg): "This directory contains Movies", with the updated information provider and scanning options underneath.

4. When I try to choose "TV Shows" instead, the selection doesn't take and I'm back at what we see in [img1].

5. Interestingly, when I go back to the content selection menu, now "TV Shows" is highlighted instead of "None" [as if it had been successfully set [img3]](https://user-images.githubusercontent.com/11735768/79290238-dda10680-7ecb-11ea-9e0f-0c60c8b96bc3.jpg).

6. Picking "Music videos" yields exactly the same results.

7. I even tried changing a video source, whose contents had previously been scanned into my library as movies, to TV shows, but that won't work either.

I'm running XBian build 20200328-0637458-dirty on a RaspberryPi 2B v1.1 with default settings.
Just to make sure before I took those photos and edited my initial post I re-downloaded the image file, flashed it onto a different SD card and used a RaspberryPi 3B+ instead, but the issue still remains. 

Any help or nudge in the right direction would be much appreciated!

**Comment by mkreisl** [comment]
Hi, I read your post tree times and still having absolutely no idea what exactly your problem is

Sorry, but at least I can change the content as often as I want

BTW, what's your nick at the forum?

**Comment by morluf** [comment]
That's what I get for trying to report a bug after pulling an all-nighter...

I apologize - I have edited my post and included visual aids. Hope it makes more sense now.

**Comment by mkreisl** [comment]
Again, I do not know what you're doing wrong.

I tested it again with a fresh kodi profile (removed /home/xbian/.kodi), but I can change content to all types I want without any problem

**Comment by morluf** [comment]
That's so weird. 
I even tried it a fourth time, re-downloading and re-flashing the image and taking care not to change a single default setting (apart from the keyboard layout) before trying to set my content.

Since you are not able to reproduce my issue it would appear to be either an operating error on my part or a faulty set-up. Thanks anyway for checking, and sorry for the inconvenience!
