### ISSUE TITLE
Error while installing xbian in raspberry pi 4 8b RAM

### ISSUE THREAD

**Issue by venkatmakam** [xbianonpi/xbian#881]
Hello,
I tried to install xbian in my raspberry pi 4.while booting it throws error
`This board required newest software`.
Also i used noobs xbian image.but xbian os is not listed in noobs os list.
Any help?

**Comment by mkreisl** [comment]
Which image did you used? I never seen this message
And, you have to use PINN

**Comment by mkreisl** [comment]
https://community.volumio.org/t/raspberry-pi-4-8gb-cannot-install-this-board-requires-newer-software/39536
If this is is the message you get, firmware files are too old.

I have to update this package (those files are located in xbian-package-firmware) and new image has to be build at Friday

**Comment by venkatmakam** [comment]
> https://community.volumio.org/t/raspberry-pi-4-8gb-cannot-install-this-board-requires-newer-software/39536
> If this is is the message you get, firmware files are too old.
> 
> I have to update this package (those files are located in xbian-package-firmware) and new image has to be build at Friday

Yes exactly, same error i am facing.

**Comment by mkreisl** [comment]
Ok, if you have an older Pi (2,,3,4(<8GBRAM)), you could put this sd card into this one and update the package xbian-package-firmware (available about in one hour).
After updating this package everything should be fine

**Comment by venkatmakam** [comment]
> Ok, if you have an older Pi (2,,3,4(<8GBRAM)), you could put this sd card into this one and update the package xbian-package-firmware (available about in one hour).
> After updating this package everything should be fine

I have RPI2.I will try tomorrow.Thank you.
Also i used the PINN installer from
https://sourceforge.net/projects/xbian/files/release/XBian_by_PINN_3.3.4_rpi.img.gz/download,but i did not see xbian either in general or any other tabs. Am i missing something?

**Comment by mkreisl** [comment]
Please use PINN from our download page

**Comment by venkatmakam** [comment]
Yes i saw rpi4 missing.I thought of adding manually,but could not tried.:)
So if i want to install xbian along with PINN i need to wait till image is updated.
But mean while i can use the [solution](https://github.com/xbianonpi/xbian/issues/881#issuecomment-658309859),for installing xbian alone.Am i right?

**Comment by mkreisl** [comment]
Yes, that's the standard way.

And, having just updated XBian's PINN version to 3.3.4.2, should work now again with Pi4 again

**Comment by venkatmakam** [comment]
Hi i did xbian-package-firmware in RP2 .But i am facing same issue in RPI4.
![Screenshot_20200715-194608315~2](https://user-images.githubusercontent.com/1190477/87561011-b67bf000-c6d9-11ea-89d0-92eabac758b9.jpg)
![IMG_20200715_195215](https://user-images.githubusercontent.com/1190477/87561017-b845b380-c6d9-11ea-8748-524f2f48517a.jpg)

**Comment by venkatmakam** [comment]
Yes it was updated correctly after changing the time zone.Now i am able to boot in RPI4.Thanks.

**Comment by mkreisl** [comment]
Thanks for confirming
