### ISSUE TITLE
Unable to connect to internet in Raspberry Pi4 (8GB RAM)

### ISSUE THREAD

**Issue by venkatmakam** [xbianonpi/xbian#882]
Hello, I have installed the latest XBIAN(Jjuly 31st) in RPI4. I have connected to WIFI, but unable to install any plugins. Installed youtube manually and tried to play, but failed.

But ping or wget (google.com) from ssh works fine.

Am i missing any thing?

**Comment by mkreisl** [comment]
Check your network please

Without any logs no furher help, sorry
