### ISSUE TITLE
[rpi4] Stuck on reboot

### ISSUE THREAD

**Issue by HagaiTz** [xbianonpi/xbian#888]
When rebooting device from menu it shows the logo with "rebooting..." underneath, and stuck on this screen.]
When re-connecting the power supply everything loads up just fine.
It also happened with the version from 10-15-2020 and with the latest version.

Running from 64GB SD card, rpi4 with 8GB ram.

**Comment by eremem** [comment]
Do you have any *actively powered* USB devices connected to the rpi4? I mean an external HDD or an USB hub with own power supply? In such a case this seems to be a "feature" of the USB standard implementation of the rpi4 (different to the previous rpi generations). More details you can read e.g. in the following [discussion](https://forums.raspberrypi.com/viewtopic.php?t=244900).
