### ISSUE TITLE
InputStream Adaptive newer than 2.6.17 

### ISSUE THREAD

**Issue by jon10220** [xbianonpi/xbian#896]
Sorry to write on github. but I cannot activate the account on forum.xbian.org.

Netflix addon requires InputStream Adaptive 2.6.18 to run in HD resolution. But the latest xbian is only 2.6.17
Where can I find InputStream Adaptive 2.6.18 compatible with xbian? 

I will be grateful for your help

**Comment by mkreisl** [comment]
This binary addon (as well as all others) is part of the **xbian-package-xbmc** package. 
You only need to update this

**Comment by jon10220** [comment]
Thanks for the update
now Netflix works in HD
