### ISSUE TITLE
How to disable the system backup warning 

### ISSUE THREAD

**Issue by FrankJian** [xbianonpi/xbian#897]
Hello , 
   we are using the XBian_2021.08.20_rpi4.img and always met the system backup pop window.
   is it possible to disable such inforamtion by system configuratin ?
![image](https://user-images.githubusercontent.com/24399952/131283332-8236badb-8c0c-463a-b66f-b54c606679eb.png)

**Comment by mkreisl** [comment]
http://forum.xbian.org/thread-3919-post-34411.html#pid34411
