### ISSUE TITLE
soundcard Chipdip DAC (dsp machine) not included in new release.

### ISSUE THREAD

**Issue by chipdipru** [xbianonpi/xbian#901]
Please add card driver snd-soc-chipdip-dac.ko. The driver is not included in the new release, but it is in the kernel along with the corresponding overlay.

![sound_soc_xbian](https://user-images.githubusercontent.com/43340836/135722588-2c7830bb-ec3b-4c76-99a2-70b74227c51f.jpg)

Sound card needs the driver to work properly.
This is a popular sound card in Russia. 
ADAU1701
![master DAC 065_1](https://user-images.githubusercontent.com/43340836/135722674-ba4a3008-2296-4c67-9bf8-4702fe1a0935.jpg)

**Comment by mkreisl** [comment]
Which driver?

I only find binary only modules from here: https://github.com/chipdipru
And including binary drivers is very suspect to me

**Comment by chipdipru** [comment]
The driver is in the kernel https://github.com/raspberrypi/linux/blob/rpi-5.10.y/sound/soc/bcm/chipdip-dac.c
Overlay and driver were added in the kernel simultaneously. But it happened somehow that only overlay was taken into account without the driver.

**Comment by mkreisl** [comment]
Ah, now it becomes clearer to me. I stupidly searched for the presence in the wrong kernel sources (5.4) and could not find anything

Next time the kernel package is built, the module is included
