### ISSUE TITLE
Latest Raspbery pi and Cubox images contain just the hash

### ISSUE THREAD

**Issue by tbertels** [xbianonpi/xbian#911]
https://sourceforge.net/projects/xbian/files/release/XBian_Latest_rpi.img.gz/download
https://sourceforge.net/projects/xbian/files/release/XBian_Latest_rpi4.img.gz/download
https://sourceforge.net/projects/xbian/files/release/XBian_Latest_imx6.img.gz/download
all contain just the hash.
The latest builds at https://sourceforge.net/projects/xbian/files/release/ with date in the name seem fine though.

**Comment by mkreisl** [comment]
Thanks for the tip. Looks like the cronjob that sets the link to the latest version is not working properly anymore

**Comment by mkreisl** [comment]
Fixed
