### ISSUE TITLE
How to add Polish language?

### ISSUE THREAD

**Issue by gilban1** [xbianonpi/xbian#917]
Hello, and I have a question - How to add Polish in Kodi? So I just want the entire program gui in my native language. Multiple languages should be listed by default, but only English is included.

**Comment by mkreisl** [comment]
https://www.youtube.com/watch?v=SCwTDpkJ2JQ

And if you also want to have the XBian-Config GUI in Polish, you have to change the language for the operating system as well. You can do this for example with the CLI program xbian-config

And by the way, this is a place to report bugs, not a help forum.
