### ISSUE TITLE
the xbian project is dead?

### ISSUE THREAD

**Issue by jon10220** [xbianonpi/xbian#921]
Hi
is there something wrong with the xbian project?
I see the last update was 14.10.2022 more than a month ago....

**Comment by mkreisl** [comment]
What a stupid question, I think there is something wrong with you. Such a topic has absolutely no place here!

**Comment by The-Exnor** [comment]
> What a stupid question, I think there is something wrong with you. Such a topic has absolutely no place here!

Probably some frustrated child or a troll.

**Comment by jon10220** [comment]
I used xbian for 2 years, now I wanted to install it again but

no update for a month
no information on the website
no information on the forum
no information on github

to me it looks like an abandoned project

now even more rude texts towards the user - a revelation!

simply the best OS in the world!

No worries, I will not return to xbian ever again

**Comment by mkreisl** [comment]
This thread shows me once again how obsessed many users are with updates.
They can no longer sleep peacefully if they don't get at least 3 updates on the system every day. Completely sick!
And if you don't get an update for 4 weeks (of course Debian has contributed to this) they immediately panic and think the project is dead.
