### ISSUE TITLE
One thing I noticed immediately, "THAT I HATE".....

### ISSUE THREAD

**Issue by BigDogBoy** [xbianonpi/xbian#924]
is that it refuses to boot, from an NTFS formatted partition; " I mean what if someone (or has) wants to use a very large flash drive to create the boot disk, yet still wants to use the spare space with Windows, and still access it with XBian, what are they supposed to do then?". Also, it's worth mentioning that there are no x86/64 images. Could you please release one?

**Comment by mkreisl** [comment]
What is this nonsense?

**Comment by The-Exnor** [comment]
> is that it refuses to boot, from an NTFS formatted partition; " I mean what if someone (or has) wants to use a very large flash drive to create the boot disk, yet still wants to use the spare space with Windows, and still access it with XBian, what are they supposed to do then?". Also, it's worth mentioning that there are no x86/64 images. Could you please release one?

LoL.
