### ISSUE TITLE
xbian-config does not run with Skin Aeon Nox Silvio

### ISSUE THREAD

**Issue by Isayso** [xbianonpi/xbian#926]
If skin Aeon Nox Silvio is activated, xbian-config Addon does not run (exeption missing skin.aeon.nox.silvio folder)

Thank You!

**Comment by mkreisl** [comment]
xbian-config GUI addon requires Estuary based skins

This will not be changed either, sorry

**Comment by Isayso** [comment]
I'm sorry to hear that, I have eye problems and the Estuary skin font is too tiny and the color contrast is weak.

**Comment by mkreisl** [comment]
Already tried other colors. I am currently also not sure if you can not also adjust the font size.
Furthermore you only need the xbian-config GUI for setup, it is not needed for normal operation.

**Comment by Isayso** [comment]
Yes, they are all white-ish on a light blue, green, red and so on background. Don't see any option beside switching to an Arial font, but no size change. I'm coming from LibreElec, but it seems that they don't fix bugs for RPIs below 4 anymore, so I'm new to xbian. The annoying audio and 60Hz bugs in Libre are gone in xbian, I like that. 

Will use Aeon anyway and if I think I need config, I can switch the skin. Thanks!
