### ISSUE TITLE
Consider switching to systemd

### ISSUE THREAD

**Issue by tbertels** [xbianonpi/xbian#939]
Things have changed since https://github.com/xbianonpi/xbian/issues/720 and systemd is now the main init in Linux distributions .
Switching to it would prevent issues with a start script preventing XBian from booting and could make it start faster both thanks to its asynchronous model.
Upstart is no longer maintained since 2014.

Since systemd is already running, could upstart scripts be gradually changed to systemd ones until XBian is ready fo the switch?

**Comment by mkreisl** [comment]
As long as XBian is still being maintained, systemd is not an option

**Comment by tbertels** [comment]
Why is that?
